### ISSUE TITLE
Various element margins etc.

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#102]
- **`<img alt="">`** (image description): 1 empty line above. text in block with 2 indents. 1 empty line below. First line starts with the word "Bilde."

First of all, we need to write some tests for all of these things.

**Comment by josteinaj** [comment]
@KariRudjord the "precedingseparator"-class; is it the same as a `<hr/>` element?

A `<hr/>` inserts (by default) a horizontal line. Like this:
<hr/>

It seems to be the same as what the precedingseparator class is intended for; i.e. a "thematic break" in the text?

**Comment by josteinaj** [comment]
Hmm, it seems like `<hr/>` is only available in old versions of the DTBook standard, so it won't be valid when used as part of our books. I suppose that's what the class is for...

**Comment by josteinaj** [comment]
Note that I've created a separate issue for poems: #135

**Comment by KariRudjord** [comment]
Everything working besides 

Imgroup - Both bildebeskrivelse: and Bilde: is added when "alt" is filled out. It seems a little to much. Now we use `<prodnote>` when we have an image description. Would that be wrong? If it is ok to proceed with that, I would like to remove the word Bildebeskrivelse: from img.

`<epigraph>` and `<div class="Rammetekst">` are tags we don't use in our book, I believe, so I exclude them from the test.

showin="xxx" is not working. It would be nice to have the possiblity to leave out text. Can it be fixed?

preceding separator - I'm not sure how to test this. Should I talk to Olav on how it is marked up in our books?

**Comment by josteinaj** [comment]
I'm not sure how image descriptions **should** be marked up, but if we do it with prodnotes now then I at least we should support that. Could you send me a couple of examples? You could ask @olavindergaard about this as well.

**showin:** Ok, I'll have another look at showin.

**precedingseparator:** if you add this class to an element (typically a p: `<p class="precedingseparator">...</p>`), then a horizontal line should be inserted before the element. It should behave the same as if you use a hr-element: `<hr/><p>...</p>`.

**Comment by matskober** [comment]
Could you not achieve the same as showin="xxx", using display: none in the
css?

**Comment by josteinaj** [comment]
Yes, that's how it's done now:

```
*[showin^="x"], *.hidden-braille {
        display: none;
}
```

(class for use in epub/html)

The rule `*[showin^="x"]` should mean "any element with a showin attribute that starts with 'x'". Since Kari reports that the showin attribute isn't working properly, I'll have to look closer at it. I have automated tests for it that succeeds so it's strange.

**Comment by matskober** [comment]
Yeah, but is this attribute something you want in your EPUBs/DTBooks? As a
default it should be showin="blp" or "xlp", so that decisions made in a
braille to paper context is not reflected in other formats? Most elements
have id's; is it not better to address this thru css only?

Mats

**Comment by josteinaj** [comment]
For DTBooks, the showin-attribute is just "the way to do it", and I don't think we need to change that.

For hiding things in HTML/EPUB we can either use `class="hidden-braille"`, and have that class defined in the CSS (as it is implemented now), or we could say that the producer has to insert "display: none;" into a style attribute, a style element, or by attaching a custom CSS file. I think using a predefined class is simpler and more readable.

**Comment by KariRudjord** [comment]
Prodnote is already working good (12356 before and 23456 behind) so we leave image description as they are now without any further tests, I think. We seldom use it, but I used it recently in some books, you can see job #1346 if you are interested. But leave out "Bildebeskrivelse" from <img alt ... would be good.

**Comment by josteinaj** [comment]
The showin attribute works for me on the server, @KariRudjord do you have an example of it not working?

input:
```xml
<p showin="blp">blp</p>
<p showin="xlp">xlp</p>
<p showin="bxp">bxp</p>
<p showin="xxp">xxp</p>
<p showin="blx">blx</p>
<p showin="xlx">xlx</p>
<p showin="bxx">bxx</p>
<p showin="xxx">xxx</p>
```

result:
```
⠃⠇⠏ (blp)
⠃⠭⠏ (bxp)
⠃⠇⠭ (blx)
⠃⠭⠭ (bxx)
```

**Comment by josteinaj** [comment]
This will be the result after removing "Bildebeskrivelse: ":

---

Input:
```xml
<!-- imggroup without caption and with non-empty alt-text -->
<imggroup>
    <img src="https://uu.difi.no/traller.jpg" alt="Tre gamle tretraller. Foto."/>
</imggroup>
```

Before removing "Bildebeskrivelse: ":
```xml
<row>⠀⠀⠀⠀⠀´bildebeskrivelse:⠀´tre</row>
<row>⠀⠀⠀gamle⠀tretraller.⠀´foto.</row>
```

After removing "Bildebeskrivelse: ":
```xml
<row>⠀⠀⠀⠀⠀´tre⠀gamle⠀tretraller.</row>
<row>⠀⠀⠀´foto.</row>
```

---

Input:
```xml
<!-- imggroup with caption and with non-empty alt-text -->
<imggroup>
    <img id="img3" src="https://uu.difi.no/traller.jpg" alt="Tre gamle tretraller. Foto."/>
    <caption imgref="img3">Gamle tretraller regnes av mange som antikviteter.</caption>
</imggroup>
```

Before removing "Bildebeskrivelse: ":
```xml
<row>⠀⠀⠀⠀⠀´bildebeskrivelse:⠀´tre</row>
<row>⠀⠀⠀gamle⠀tretraller.⠀´foto.</row>
<row/>
<row>⠀⠀⠀⠀⠀´bildetekst:⠀´gamle⠀tre-</row>
<row>⠀⠀⠀traller⠀regnes⠀av⠀mange⠀som</row>
<row>⠀⠀⠀antikviteter.</row>
```

After removing "Bildebeskrivelse: ":
```xml
<row>⠀⠀⠀⠀⠀´tre⠀gamle⠀tretraller.</row>
<row>⠀⠀⠀´foto.</row>
<row/>
<row>⠀⠀⠀⠀⠀´bildetekst:⠀´gamle⠀tre-</row>
<row>⠀⠀⠀traller⠀regnes⠀av⠀mange⠀som</row>
<row>⠀⠀⠀antikviteter.</row>
```

**Comment by KariRudjord** [comment]
OK
