### ISSUE TITLE
Exclude images by default

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#105]
*from Karis google sheet*:

Change to default: exclude. It's better to include when needed. (our producers add "image" in the alt attribute - it takes too much space in the productions).

**Comment by josteinaj** [comment]
@KariRudjord we could alternatively treat images with the alt text "image" the same way as images with an empty alt text, which means they would be excluded. Only if the alt text is not empty and not "image", would the image be included. What do you think?

**Comment by KariRudjord** [comment]
I think that would be a good idea, @josteinaj

**Comment by KariRudjord** [comment]
Working
