### ISSUE TITLE
Dash

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#109]
*from Karis google sheet:*

Dash - or --

**Comment by KariRudjord** [comment]
Works.

**Comment by KariRudjord** [comment]
- En dash in unicode U+2013 (&#8211; HTML Entity (decimal)) - works
But en dash &#x2013; does'nt work. (HTML Entity (hex) I'll sheck more on monday.

— Em dash when marked in unicode: U+2014 (&#8212;) - works

**Comment by KariRudjord** [comment]
Statped:
rejoinder streak (replikkstrek) should also be (36-36) in braille. (Space before and after). Unicode — "&#x 2013;"

**Comment by KariRudjord** [comment]
Two things not working yet:
1. En dash when marked in unicode &#8211; should be (36-36) 
2. Minus sign when marked in unicode &#8722; should be (36)

**Comment by KariRudjord** [comment]
Works.
