### ISSUE TITLE
Add a report document with information about the PEF

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#11]
_From @josteinaj on May 20, 2016 12:4_

The report should include the total number of PEF pages (i.e. XPath `count(//pef:page)`)

(Note that this is not a high priority, we can do this after the main project is finished if necessary)

CC @KariRudjord 

_Copied from original issue: nlbdev/pipeline-mod-nlb#46_

**Comment by josteinaj** [comment]
Should include information about whether or not the book contains tables.

**Comment by josteinaj** [comment]
@KariRudjord do you think we need a separate report document or is the HTML preview enough?

**Comment by KariRudjord** [comment]
What I wish for, is a report to look into every morning to check whether the files produced the last 24h have success or have failed, and if any of the productions include tables. 

After a test period where I check all productions I think we might trust that ordinary productions are correct without checking. And can concentrate on working with the files containing tables. (Maybe this is to optimistic?) 

We also need a way to automate adding pages and volumes to Quickbase, and check the production out in Quickbase. Do you think that is possible?

**Comment by josteinaj** [comment]
The production system sends out e-mails whenever a PEF is produced. It will say if the production succeeded or if it failed. We could also include information about whether there are tables in the book there. Would that be sufficient?

Adding pages and volumes to Quickbase; we could probably implement that. But is it necessary? Isn't it enough to have it in Bibliofil?
