### ISSUE TITLE
Support roman numerals

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#110]
*from Karis google sheet*

**Comment by KariRudjord** [comment]
Capitals - 6 before
Lower case - 56 before

**Comment by matskober** [comment]
Don't we need to mark up roman numerals inline, like 'Haakon IV' or 'Haakon VI'? Otherwise, how to differ between roman numerals and clusters of capital letters?

**Comment by KariRudjord** [comment]
I don't know if its possible to solve the roman number issue. How should you know if Magnus V Magnussen is Magnus 5th or Magnus Verner Magnussen?

**Comment by matskober** [comment]
If only one numeral or letter I guess it doesn't matter; then V is ⠠⠧
anyway, right ? But when more than one; VI = ⠠⠠⠧⠊ (alphabetical) or ⠠⠧⠊
(numeral).

**Comment by KariRudjord** [comment]
Could we do something for all the numbers containing of mor than one letter? What about 100, 500, 1000?
I 1
II 2
III 3
IV 4
V 5
VI 6
VII 7
VIII 8
IX 9
X 10
XI 11
XII 12
XIII 13
XIV 14
XV 15
XVI 16
XVII 17
XVIII 18
XIX 19
XX 20
XXV 25
XXIX 29
XXX 30
XXXV 35
XXXIX 39
XL 40
XLV 45
XLIX 49
L 50
XC 90
C 100
D 500
M 1000
MCC 1200
MDXXXVI 1536
MDCLXVI 1666
MDCCLXXXVIII 1788
MCM 1900
MCMXC 1990
MCMXCVIII 1998
MM 2000

**Comment by josteinaj** [comment]
I think multiple capital letters are already surrounded by "⠠⠠" on each side?

Also, I think things would be much easier if we didn't have to detect whether something is a roman numeral or not.

**Comment by matskober** [comment]
The sensible thing would be to get OUP to adjust the rule? Why should 'Haakon VI' (⠠⠓⠁⠁⠅⠕⠝ ⠠⠠⠧⠊) be worse than 'Haakon Vi' (⠠⠓⠁⠁⠅⠕⠝ ⠠⠧⠊)? Today's rule only make sense (inline) if the roman numerals are in lower case, when ⠰ (56) should be applied. But then again: The roman numerals need mark up or detection of some kind. (Not even sure if lower case roman numerals ever appear inline?)

**Comment by KariRudjord** [comment]
Arne is going to OUP meeting tomorrow. I have asked him to ask for the draft of new guidelines if possible. Maybe they have done something with this, we'll see.

**Comment by KariRudjord** [comment]
From Statped:
Roman numbers should only have one big letter sign (6) before the first letter.

**Comment by bertfrees** [comment]
I'm sorry, the requirement is not entirely clear to me. Would it be possible to give some examples that I can turn into a Liblouis test?

**Comment by KariRudjord** [comment]
The norwegian braille authority has changed the rules (January 31, 2019). Capital roman signs, eg. IV are now written with (6-6) before and iv is written as it is with no sign before. Works in PIP already.
