### ISSUE TITLE
When unknown characters are encountered - replace them with spaces

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#113]
*from Karis google sheet*

**Comment by josteinaj** [comment]
We currently use dot 26 for unknown characters. See #146.

@KariRudjord Should we change it do a space character?

**Comment by KariRudjord** [comment]
26 is question mark and can be misunderstood. I think we should change it to space character, yes!

**Comment by josteinaj** [comment]
Ok, then I'm keeping the issue open and moving it to the Q1 2018 project board.
