### ISSUE TITLE
Spaces in numbers should be removed

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#12]
_From @KariRudjord on May 20, 2016 13:32_

E.g. 10 000, telephone 22 08 34 57 or 3095 05 55555. Is it possible to make a rule so that space between digits is removed? (To avoid new number sign in the middel of the number or splitting in two rows when in end of a row)  

@bertfrees @josteinaj 

_Copied from original issue: nlbdev/pipeline-mod-nlb#47_

**Comment by josteinaj** [comment]
We can remove spaces between numbers during preprocessing by using a regex. @bertfrees is it easier and/or more efficient to do it somewhere other then during preprocessing?

**Comment by josteinaj** [comment]
_From @bertfrees on May 20, 2016 14:39_

I don't know about more efficient. But it could also be done in Liblouis I guess. And the more you can move to Liblouis the more useful it'll become outside the Pipeline.

**Comment by josteinaj** [comment]
Ok. I don't know (or have time to get to know) how to do that in liblouis.

@egli: would SBS be interested in solving this issue in liblouis? Otherwise we'll do it in our preprocessing XSLT.

**Comment by usama49** [comment]
please see (8.2 Tall inndelt i siffergrupper) in punkt handbook

**Comment by josteinaj** [comment]
Created related NLBPUB issue here: nlbdev/nlbpub#8

**Comment by KariRudjord** [comment]
From Statped:
- Telephone numbers: digit groups should be divided with dot (3), not space. Number sign only at the beginning, not in every group. E.g. 900 56 107 should be written 900.56.107 ⠼⠊⠚⠚⠄⠑⠋⠄⠁⠚⠛
- Dot (3) in big numbers (not space) and no number sign after dot. E.g. 100.000 kr ⠼⠁⠚⠚⠄⠚⠚⠚⠀⠅⠗
- Number sign must never be divided from the number in end of row
- measurement unit should not be divided from number in end of row. E.g. 2 m, 3,14 pi, 1,5 kg

**Comment by KariRudjord** [comment]
Braille spesific practice.  Can't be done automatical so it is right for all situations. Use classes to decide (Jostein). Might get a report for each production (like SBS). 
Open space should be replaced with dot (and no following number sign).
