### ISSUE TITLE
Volume splitting: there should always be something other than generated content in volumes

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#122]
Volume 1 has less available pages than volume 2, because volume 1 has a generated about page, while other volumes does not. If the first chapter fits in volume 2 but not in volume 1, then volume 1 will only consist of the about page. I'm not sure if this will be a problem in practice though. Ideally we should have a CSS solution. A workaround could be to insert the about page in all volumes, and then delete it from all volumes except the first in the output PEF.

*NOTE: I will commit and push xprocspec test for this one soon*

**Comment by josteinaj** [comment]
I think this would occur very often actually. It seems to occur whenever the first chapter doesn't fit in the first volume; regardless of whether it fits in the second volume or not.

**Comment by bertfrees** [comment]
But, is it really a problem? It sounds like by trying to fix this we'll end up with a less optimal volume splitting.

**Comment by bertfrees** [comment]
Unless of course the volume splitting isn't optimal right now (not taking into account whether pages are generated or not; whether pages are generated or not doesn't really matter IMO).

**Comment by josteinaj** [comment]
The result now is that the first volume will usually just consist of a couple of pages. I'm going to try some `volume-break-before: avoid;` and see if that helps.

**Comment by josteinaj** [comment]
By the way, this only happens locally for me since I haven't pushed the frontmatter changes yet. I'm working on getting those changes to pass the tests, which is why I found this issue. I'll just assign this to me until I've pushed the tests.

**Comment by josteinaj** [comment]
Tests added:
- https://github.com/nlbdev/pipeline/commit/5b9d92ffe1fc123a192360e3c91d5377753eb870#diff-0ffc6ea8a876071ea0723b93bba79ecaR25
- https://github.com/nlbdev/pipeline/commit/5b9d92ffe1fc123a192360e3c91d5377753eb870#diff-0ffc6ea8a876071ea0723b93bba79ecaR91

**Comment by KariRudjord** [comment]
After Jostein did a minor adjustment in TOC headline (longer boarders) I noticed that some productions (not all) get only generated content in volume one (just a few pages) and first chapter starts in volume 2. Maybe this have a connection? eg job 1690

**Comment by matskober** [comment]
It seems to be a pattern, although I'm nut sure; Books without anything besides docauthor and doctitle in DTBooks frontmatter works fine, if any object in frontmatter, bodymatters content starts in volume 2.

**Comment by josteinaj** [comment]
Ah, that makes sense. We have a rule matching "the first level1" that says that we would rather break the level1 in two volumes than not have any content in the first volume. However, there's a "first level1" in both frontmatter and bodymatter (and rearmatter).

**Comment by josteinaj** [comment]
@matskober I've updated the SCSS slightly, attempting to fix the issue you described with frontmatter/bodymatter. Could you check if it's still a problem? It doesn't fix this whole issue, but it might help with you specific case.

**Comment by matskober** [comment]
It seems to work now. But class="jacketcopy" results in a page with a
couple of braille signs. I added a css with .jacketcopy{display:none;}, and
it seemed to work fine. Maybe include this to the main css?

Mats

**Comment by josteinaj** [comment]
Sure, we can add a rule for jacketcopy.

"jacketcopy" is the old name for "cover" right? Do we still use "jacketcopy"?

**Comment by matskober** [comment]
well, it's in DTBook, but not in EPUB i guess?

**Comment by matskober** [comment]
Turns out there still some problems with volume spliting, see job #1804.

Mats

**Comment by bertfrees** [comment]
@josteinaj This issue was assigned to me. But what exactly do you want me to do? Verify that your  new CSS makes sense? Or verify whether the formatter does what you specified with the CSS?

I just ran your two tests, after fixing what I think was a missing comma in the CSS. The first test ("There should always be something other than generated content in the PEF, even though that means splitting a chapter that would've fit in a separate volume") returns a single volume. When I change maximum-number-of-pages from 10 to 8, it passes. And the second test ("If a book consist of more than the set max page number, it must be split into volumes: seeking a balanced page number between these volumes") passed.

**Comment by josteinaj** [comment]
@bertfrees Thanks for trying the tests, that's all that's needed :+1:. I'll keep this issue open so that we remember to re-enable the tests.

**Comment by josteinaj** [comment]
This seems to work fine. I've reenabled the two tests for this one.

@bertfrees unless you think there's something more to do here you can move this to "Ready for test".

**Comment by bertfrees** [comment]
OK good. There was still the missing comma, but apparently that had no effect on the test outcome. I've committed my fix.

**Comment by KariRudjord** [comment]
I've tested several books, but haven't been able to recreate the bug, so I guess this is actually working now :-)
