### ISSUE TITLE
Page count for one-sided books

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#123]
The page counter on the about page ("om boken") currently counts sheets instead of pages, so for two-sided (duplex) PEFs, that should be multiplied with 2 to get the correct number of pages.

@KariRudjord how many pages are there in a one-sided book? do we count the backside of each page as a page? I suppose not?

**Comment by josteinaj** [comment]
Divide sheets by 2 in 42bd7bdbe24d30d07dbc1ecd6ef2fcf332e52673. Now only need to determine how many pages there are per sheet in a one-sided (simplex) book.

**Comment by KariRudjord** [comment]
For the publisher we need to count the empty pages also, its important for the size of the volumes and the volume breaking. But for the reader (in "Om boka") we should only count the pages with print on.

**Comment by josteinaj** [comment]
When counting emty pages for the publisher; that's only for cataloging and reporting purposes, right? Not something that should be written in the PEF?

**Comment by KariRudjord** [comment]
It's to secure that the volumes contains maximum 86 pages (whether they have print or not). If the volumes get thicker, they get problems with the stapling.

**Comment by josteinaj** [comment]
Oh, right.

**Comment by bertfrees** [comment]
I haven't been following this issue. What exactly has been done and what is left to do?

**Comment by josteinaj** [comment]
I'm not sure if much has been done. Maybe @KariRudjord should test this first?

**Comment by bertfrees** [comment]
@KariRudjord I have fixed the page count on the about page. However, as we discussed this morning, it might still not be exactly what you expect (so we might remove it altogether).

I'm now going to add the page count to the PEF metadata, so that you can easily extract this information when you generate an email. Could you explain what exactly the number should be? Count everything? Skip frontmatter? Include empty left-hand pages?

**Comment by matskober** [comment]
This seems to be the "pages vs. sheets debate" all over again; The Embosser
Firm / printing agency needs to know the number of sheets in scope -
regardless of whether the pages are empty or not - but to the reader the
empty pages are less interesting - they are more into the content ...

So, it is actually two different issues: a book consist of the same number
of (content-) pages regardless of single sided or duplex printing, but the
number of sheets used differ.

Mats

**Comment by bertfrees** [comment]
OK thanks I know enough.
