### ISSUE TITLE
Problem inserting titlepage and about page in EPUB

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#124]
`err:XTRE0540:Ambiguous rule match for /html/body[1] Matches both "html:body[tokenize(@class,'\s+') = 'titlepage' or tokenize(@epub:type,'\s+') = 'titlepage']" on line 67 of bundle://88.0:1/xml/insert-boilerplate.xsl and "html:body[not(preceding::html:body)]" on line 30 of bundle://88.0:1/xml/insert-boilerplate.xsl`

Job on test server: 1086

Structure outline:
```html
<html>
<head>...</head>
<body epub:type="frontmatter titlepage" id="f1">...</body>
<body epub:type="frontmatter colophon" id="f2">...</body>
<body epub:type="bodymatter chapter" id="ch1-1">...</body>
...
</html>
```

Reported by @matskober

**Comment by josteinaj** [comment]
Preprocessing was updated for all scripts in d1dd47fee77b1795e2f1f7736c6abb5542adaaf2.

This should be re-tested.

**Comment by KariRudjord** [comment]
Tested with two random EPUBs. Works
