### ISSUE TITLE
Volume TOC should start on page 2

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#126]
...or in other words, the TOCs should end up in the first `<section>` in each `<volume>` of the PEF.

**Comment by josteinaj** [comment]
Tests added in 1ba1b4aac9ac9ce89f1b072ee0a9300c908509b2

**Comment by bertfrees** [comment]
Not possible at the moment, see https://github.com/braillespecs/obfl/issues/48.

**Comment by KariRudjord** [comment]
Is this a double card @josteinaj 
As far as I can see, TOC appear on page 2 in other volumes than the first. Can I move this one to done?

**Comment by josteinaj** [comment]
@KariRudjord In one sided PEFs it should work, but in two-sided PEFs ("duplex") you should currently get the TOC appearing on the right page instead of the left page. Maybe it's still numbered as page 2 and maybe it's not showing properly in the PEF preview, I don't know. Have you tried opening a PEF in some other embossing utility to see which page it appears on?

**Comment by bertfrees** [comment]
This is not blocked on Dotify anymore. But is this issue still valid? See also https://github.com/nlbdev/pipeline/issues/78.

**Comment by KariRudjord** [comment]
Sorry, this should have been closed.
