### ISSUE TITLE
Automatically test all hyphenation rules

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#13]
_From @josteinaj on May 31, 2016 13:29_

Leaving out substrings.pl from the dictionary generation might be a bad idea: https://github.com/snaekobbi/pipeline-mod-nlb/commit/ed0275a686f7369f84387741522518451e3ac7dc#commitcomment-17678339

...or maybe not. We'll have to test it more thoroughly.

_Copied from original issue: nlbdev/pipeline-mod-nlb#50_

**Comment by josteinaj** [comment]
@usama49 I'm assigning you to this, is that ok?

**Comment by josteinaj** [comment]
@KariRudjord @matskober Have you observed any working / non-working examples of hyphenation in your tests? Could we safely say that hyphenation is working well now?

**Comment by josteinaj** [comment]
We have several automated tests, and hyphenation seems to happen as expected during conversion of books in practice. We could do more testing with different words etc, but I doubt we'll actually have time to do that. Let's instead revisit hyphenation if we discover problems later.

**Comment by bertfrees** [comment]
I'm still not sure about the substrings thing. Do you at least test that all the words from [words.txt](https://github.com/nlbdev/pipeline/blob/nlb/modules/nlb/book-to-pef/src/main/resources/hyph/hyph_nb_NO_standard_dictionary/words.txt?raw=true) are hyphenated correctly?

**Comment by bertfrees** [comment]
Should be quite straightforward to add such a test.

**Comment by josteinaj** [comment]
I don't think we automatically test them all, no.

So the worry is that some of the non-standard hyphenation rules may break some of the standard hyphenation rules?

**Comment by bertfrees** [comment]
The worry is that the as far as I know required "substrings.pl" step is not performed.

**Comment by josteinaj** [comment]
Ok, I'll change this issue to be about automatic testing and reopen it.

**Comment by bertfrees** [comment]
You say you removed the step because "[it merges standard and non-standard hyphenation rules which for some reason causes problems](https://github.com/nlbdev/pipeline-mod-nlb/commit/ed0275a686f7369f84387741522518451e3ac7dc)". But instead of removing it altogether you might get better results if you just move it in front of the step that concats hyph_nb_NO_standard.pat and hyph_nb_NO_nonstandard.pat?

**Comment by josteinaj** [comment]
Ok, I'll try that (when I get around to it).
