### ISSUE TITLE
TOC - full TOC in vol.1

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#130]
Volume spesific TOC in other volumes
Now it is vol spesific TOC in volume one.

**Comment by josteinaj** [comment]
Oh, I forgot to change that. I'll fix it.

**Comment by josteinaj** [comment]
Should be fixed now. @KariRudjord you can try again.

**Comment by KariRudjord** [comment]
I've tried with a random book and with the test book I used in the AT. Both failed, @josteinaj 
Book is only produced when it's only one volume.+

**Comment by KariRudjord** [comment]
But when I try another book (used in AT) it works. So maybe something was wrong with the book I used first. Should I maybe try with more books, @josteinaj ?

**Comment by josteinaj** [comment]
If it works in some books but not all, that's still a bug we should fix. Maybe you can try the books that failed previously one last time, and if they still fail I'll have a closer look at them.

**Comment by KariRudjord** [comment]
E.g. 501349 (study book) and 550220 (childrens book with simple TOC)  failes.

**Comment by bertfrees** [comment]
I have tried to convert the 550220 and it worked fine. Maybe my latest volume breaking related changes have something to do with it. @KariRudjord please test again when the latest version has been deployed.

**Comment by josteinaj** [comment]
Deployed. @KariRudjord ready for test.

**Comment by KariRudjord** [comment]
Works.
