### ISSUE TITLE
Lists with markup <pl> shall have layout as<ul> og <ol>

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#132]
That is: start from left marin. When text is more than one row, text start with 2 indents from row 2.

**Comment by josteinaj** [comment]
Does this not work? I have [a test for it](https://github.com/nlbdev/pipeline/commit/2fbf30c3cc1de11bc54c51eca495d6544de83eb1#diff-afc793f7973a615c02206712f8c2c5baR2172) that passes:

input:
```xml
<list type="pl">
    <li>content content content content content content content content</li>
    <li>content content content content content content content content</li>
    <li>content</li>
    <li>content</li>
    <li>content</li>
    <li>content</li>
    <li>content</li>
    <li>content</li>
    <li>content</li>
    <li>content content content content content content content content</li>
</list>
```

output:
```xml
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row/>
```

**Comment by josteinaj** [comment]
...or maybe it's an EPUB issue? There's no test  for that currently.

**Comment by matskober** [comment]
If you skipped to left margins ?

<row>⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row>⠀⠀⠉⠕⠝⠞⠑⠝⠞⠀⠉⠕⠝⠞⠑⠝⠞</row>
<row/>

**Comment by matskober** [comment]
two ...

**Comment by josteinaj** [comment]
All pages have a two-cell gap at the left. Probably to allow for page markers. So you can disregard the two first cells in my example for this particular issue, since those cells are not really part of how the list is styled. If we removed that margin, we would get the same as your example.

**Comment by matskober** [comment]
ok. Do it do this a standard? If I wouldn't want them; would I have "to go
negative" on the margin? (-2?)

Mats

**Comment by josteinaj** [comment]
The [current rule](https://github.com/nlbdev/pipeline/blob/nlb/modules/nlb/book-to-pef/src/main/resources/css/nlb-default.scss#L17) looks like this:

```css
@page {
        margin-right: 1;
        @if $show-print-page-numbers {
            margin-left: 2;
        } @else {
            margin-left: 1;
        }
}
```

So there's always 1 empty cell on both the left and right side of the page. And if the `show-print-page-numbers` option is enabled ([which it is by default](https://github.com/nlbdev/pipeline/blob/nlb/modules/nlb/book-to-pef/src/main/resources/xml/xml-to-pef.xpl#L192)), then there's 2 empty cells on the left (i.e. an empty column used for page markers).

You could try disabling the `show-print-page-numbers` option and adding this CSS to remove the margin altogether:

```css
@page {
        margin-left: 0;
}
```

**Comment by KariRudjord** [comment]
Empty row over table is put into CSS.
