### ISSUE TITLE
List type dl

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#133]
Some books have list type dl. Find a good rule for this. 

Eg.:
 <dl>
  <dt>Coffee</dt>
  <dd>Black hot drink</dd>
  <dt>Milk</dt>
  <dd>White cold drink</dd>
</dl>

**Comment by matskober** [comment]
When I come across dl-lists, I turn them into pl-lists, replacing the
closing dt-tag and the following (opening) dd-tag with colon and
withespace. (Opening dt and closeing /dd becomes li and /li)
<li>Coffee: Black hot drink</li>
<li>Milk: Withe cold drink</li>

**Comment by josteinaj** [comment]
Making it into a list sounds good. An alternative would be to just give all `dd` elements a 2 cell left margin.

Note that definition lists can also have multiple definitions per definition term. For instance:

 <dl>
  <dt>Coffee</dt>
  <dd>Black</dd>
  <dd>Hot</dd>
  <dd>Drink</dd>
  <dt>Milk</dt>
  <dd>White</dd>
  <dd>Cold</dd>
  <dd>Drink</dd>
</dl>

So, making it into a list (joining multiple definitions with a comma):

```xml
<row>  Coffee: Black, Hot, Drink  </row>
<row>  Milk: White, Cold, Drink   </row>
```

Or, using indentation:

```xml
<row>            </row>
<row>  Coffee    </row>
<row>    Black   </row>
<row>    Hot     </row>
<row>    Drink   </row>
<row>  Milk      </row>
<row>    White   </row>
<row>    Cold    </row>
<row>    Drink   </row>
<row>            </row>
```

We can also consider rendering the definition terms in bold.

**Comment by matskober** [comment]
I believe that comma separation would be preferable in a braille context.
(Easier to navigate, less space consuming.)

**Comment by bertfrees** [comment]
FYI: https://github.com/sbsdev/pipeline-mod-sbs/issues/69

**Comment by KariRudjord** [comment]
em and strong within dl: the file will not go through PIP. Find a way to fix this.
