### ISSUE TITLE
CSS for poems

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#135]
@KariRudjord do you have an example of a poem produced with NorBraille? If not, I can just make a suggestion?

**Comment by KariRudjord** [comment]
CSS for poems virker fint i PIP, sjekket akkurat. Men her er et dikt i NorBraille, om du trenger det.

![image](https://user-images.githubusercontent.com/12409918/31939713-bc870676-b8bb-11e7-8b56-6af1b3aa6114.png)

**Comment by josteinaj** [comment]
Åja virker det? Trodde ikke det jeg. Skal uansett lage en test for det. Takk for eksempel :)

**Comment by KariRudjord** [comment]
Ammar og jeg la det inn for lenge siden :-)

**Comment by KariRudjord** [comment]
Kan jeg parkere dette kortet, @josteinaj  eller har du planer for det?

**Comment by josteinaj** [comment]
Har ingen planer for det, så om det fungerer fint må du gjerne parkere det :)
