### ISSUE TITLE
First half of word is deleted when non-standard hyphenation break point is at page width

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#14]
_From @josteinaj on June 3, 2016 13:30_

To illustrate, these three lines represent the page width, box/paragraph width, and braille text (shown as characters). As I see them in the PEF:

```
|----------------------------|            (page width 30)
  |------------------------|              (26 cells left after 2 padding left/right)
  VOLLEYBALLEDEREN VOLLEYBALLEDEREN
```

In this case, the paragraph box ends between `VOLLEYBAL` and `LEDEREN`, which is also the hyphenation point for the word `VOLLEYBALLEDEREN`. Hyphenated, the word should be `VOLLEYBALL-LEDEREN`

I tested with a standard hyphenation word as well (SAMMFUNNSFORSKERE) to see if the same problem occurs there when the hyphenation point coincides with the box width, but it does not. So I think the problem here is that for non-standard hyphenation, an extra character is inserted, making that part of the word too long to fit, and as a result that part of the word is deleted. The result after hyphenation from the previous example is:

```
|----------------------------|
  |------------------------|
  VOLLEYBALLEDEREN LEDEREN
```

_Copied from original issue: nlbdev/pipeline-mod-nlb#51_

**Comment by josteinaj** [comment]
_From @bertfrees on June 3, 2016 13:38_

Oops, that's a bug alright!

**Comment by josteinaj** [comment]
_From @bertfrees on June 10, 2016 10:50_

You were going to provide a test in mod-nlb right?

**Comment by josteinaj** [comment]
Oh, right, yeah I can do that. Thanks for reminding me.

**Comment by josteinaj** [comment]
@bertfrees test added to branch `issue-51`.

**Comment by josteinaj** [comment]
@usama49: this needs to be high on our list for testing.

**Comment by josteinaj** [comment]
This seems to work now. Added a regression test.

**Comment by bertfrees** [comment]
For reference, it was fixed in https://github.com/daisy/pipeline-mod-braille/commit/eb2a8dc9ae425ce8c16ae996f23305fab4aa1704.
