### ISSUE TITLE
Check that overriding CSS works

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#140]
Attach a CSS stylesheet containing a rule that overrides something in our default CSS and see that the attached CSS overrides the default CSS.

See default stylesheet here: https://github.com/nlbdev/pipeline/blob/nlb/modules/nlb/book-to-pef/src/main/resources/css/nlb-default.scss

For instance:
```css
p {
        text-indent: 10;
}
```

**Comment by KariRudjord** [comment]
Works for `<p>` but not for remove the word Margtekst in `<sidebar>`. @usama49 will look at it

**Comment by KariRudjord** [comment]
Tested with lists and p. Works.
