### ISSUE TITLE
No "actual content" in first volume

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#143]
For job #1439 (DTBook 561859) first volume only contain titlepage, Om boka, TOC and colophone - no text of the book (contain 11 pages).  Seems like a regular novel, so I can't figure out why.

**Comment by josteinaj** [comment]
Job: 1439
Book ID: 561859

After preprocessing the book should end up with a level1 colophon and a level1 containing only an image that will not be rendered. Next is bodymatter, and the bodymatter is not rendered until the next volume.

**Comment by KariRudjord** [comment]
Another example is job 1873 where vol 7 contains only generated content and a level1 Part (not chapter)

**Comment by josteinaj** [comment]
#119 is due to the same issue I think.

**Comment by bertfrees** [comment]
Isn't this the same issue as https://github.com/nlbdev/pipeline/issues/122?

**Comment by josteinaj** [comment]
It's quite similar to #122, but I think maybe this is an issue about there not being any "actual content" (i.e. the first chapter) in the first volume (so a stricter version of #122 I suppose). We should probably prevent there being only a "part" headline or foreword in the first volume if that makes the first volume very small. Right @KariRudjord?

This is something we can probably fix in CSS with `-obfl-keep` rules, so I'm unassigning you @bertfrees.

**Comment by KariRudjord** [comment]
Yes, and seems like its fixed now. When retesting the two test examples, I get a much better result with thick volumes. 

I tried a study book (559880) with lots of things in frontmatter, preface etc, and it worked fine. But two of the volumes contains very few pages. Vol. 6 is 30 pages and stops inside av level2. Vol. 14 is 24 pages and ends on the end of a part two. I don't understand why. Job #2038 I move this to a new card with low priority.
