### ISSUE TITLE
Handling of big tables

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#145]
How shall we handle big tables? I guess they sometimes must be left out of the production, but in many cases they can be transformed to text.

Can we have an error message saying: Table to large or something like that - and then go through it manually to decide behaviour?

If nothing else is possible, we can manipulate the sourcefile manually as we do today.

**Comment by bertfrees** [comment]
I think Jostein had something in mind with analyzing the table in a preprocessing step and setting a class based on some "size" criteria (see https://github.com/nlbdev/pipeline/issues/8#issuecomment-339330343). It is also possible to make a decision during formatting (within Dotify) but that will require a bit of work to integrate this Dotify feature (see https://github.com/nlbdev/pipeline/issues/8#issuecomment-339313724). An error message is of course possible, that is basically the behavior right now: see https://github.com/nlbdev/pipeline/issues/129 (except the error message could be a bit nicer).

**Comment by josteinaj** [comment]
Is "big tables" still an issue? Even big tables can be represented as lists, right?

**Comment by KariRudjord** [comment]
I tried one of Statpeds books (561686) and there is some grammar set as table. It is put in the log under Malformed tables. I guess the best way for such tables is table-to-list. Since we get the message Malformed, we can go in for such complicated tables and decide.
