### ISSUE TITLE
EPUB: <hr class="emptyline"/>, makes emptyline , 3 x dots 36, emptyline

### ISSUE THREAD

**Issue by matskober** [nlbdev/pipeline#148]
![image](https://user-images.githubusercontent.com/8014898/33201775-d4679a3c-d0f1-11e7-828e-a7a17630eed4.png)

It should be only one empty line

Job #1633

**Comment by josteinaj** [comment]
We don't have a `emptyline` class defined.

We have a `precedingseparator` class, which is meant for DTBook where `<hr>` is invalid.

We do have `precedingemptyline` in our books, but we haven't defined what that should do in braille yet; it probably should just add a cell to the top margin.

`<hr/>` is a thematic break. We currently render it as in your example; as `⠔⠔⠔` with an empty row above and below. Do you want a thematic break in the content without such a marker? Or do you just some empty space? You could maybe use `<br/>` instead (although we don't currently define `<br/>` in our CSS)?

@bertfrees how would CSS for a `<br/>` element look like? Something like this?
```css
br::after { content: "\n"; }
```

**Comment by matskober** [comment]
So it should not be any 'hr class="emptyline"' in Nordic EPUBs? 
In my opinion it should be just an empty line.
![image](https://user-images.githubusercontent.com/8014898/33204201-b126f58c-d0fa-11e7-9d83-ac7313a9919f.png)
(561900)

**Comment by josteinaj** [comment]
I found this in our procurement spec, so you're right 😊:

> ## 4.11 Structure Requiring `<hr>` Markup
> Titles that do not provide the same depth of navigation through heading structures may provide meaningful structure by using the common practice of indentation and/or empty lines to indicate a ‘paragraph-level thematic break’. In those circumstances where depth of structure is not amenable to structural markup using sectioning markup, Suppliers are required to provide the following structural markup to distinguish paragraph-level thematic breaks:
> - `<hr class="emptyline"/>` - The `<hr>` element must be used with `class="emptyline"` to indicate thematic breaks represented by an empty line between paragraphs.
> - `<hr class="separator"/>` - The `<hr>` element must be used with `class="separator"` to indicate thematic breaks represented by a visual marker such as an asterisk or horizontal rule between paragraphs. The visual marker must not be rendered in the content document.

So it seems `emptyline` is indeed a class we might get in EPUB.

I see also from the nordic migrator that the EPUB3 classes `emptyline` and `separator` in this context is converted to a `precedingemptyline` and `precedingseparator` on the fist following element.

I would imagine that `<hr class="emptyline"/>` would render as three empty lines though? So that it takes up as much space as a `<hr class="separator"/>`? Or maybe not?

@KariRudjord do you have any thoughts on this?

**Comment by bertfrees** [comment]
@josteinaj &lt;br/&gt; is already defined like that.

**Comment by josteinaj** [comment]
@bertfrees ah, in the inherited default.css, I see. Cool.

**Comment by matskober** [comment]
@bertfrees says :  br/ is already defined like that.

Like what? One empty line -  or like it turned out above?

**Comment by bertfrees** [comment]
Like a single newline (not two).

**Comment by bertfrees** [comment]
https://github.com/daisy/pipeline-mod-braille/blob/c6f8e173ecf270d041d02ef6cc0300a45c9f58e0/pipeline-braille-scripts/dtbook-to-pef/src/main/resources/css/default.css#L62-L65
