### ISSUE TITLE
hyphenation

### ISSUE THREAD

**Issue by matskober** [nlbdev/pipeline#150]
The word 'that' are hyphenated t-hat, at least two times on two pages ... 
Is there a 'don't do (t-hat)' list?

![image](https://user-images.githubusercontent.com/8014898/33210144-ea96bdbe-d110-11e7-9e37-6dae98841d44.png)

**Comment by josteinaj** [comment]
Not sure why, but only norwegian text should get hyphenated so in this case the language code is probably wrong? If "that" were a norwegian word, I don't know how I'd hyphente it. t-hat would be as good as anything.

**[Words containing "th"](http://ord-med.finn-et-ord.net/ord-med-th.html):**

- Aarset-h
- abort-hyppighet
- abort-hyppigheta
- abort-hyppighetene
- absolutt-hetskrav
- actiont-hriller
- advokat-hjelp
- advokat-hjelpa
- advokat-hjelpene
- advokat-hjelper
- advokat-hold
- advokat-honorar
- affektert-het
- affektert-heta
- Agat-ha
- aggregat-hus
- akutt-hjelp
- alabast-hvit
- alabast-hvitt
- alkoholist-heim
- alkoholist-heimene
- alkoholist-hjem
- alkoholist-hjemmet
- alt-horn
- alt-hornet
- angst-hysteri
- angst-hysteriet
- ankomst-hall
- ankomst-hallene
- ankomst-hamn
- ankomst-hamnene
- ankomst-havn
- ankomst-havnene
- annet-hopp
- annet-hoppa

**[Words starting with "th"](http://ord-som-starter.finn-et-ord.net/ord-som-begynner-th.html):**

- t-hai
- t-haiene
- T-hailand
- t-hailandsk
- t-hailender
- t-hailendere
- t-hailenderen
- t-hailending
- t-haisilke
- t-haisilkekjolen
- T-halia
- t-halidomid
- t-halidomidbarn
- t-halidomidet
- t-halidomidoffer
- t-halidomidtragedie
- t-hallium
- t-halliumet
- T-hames
- T-harald
- T-haraldsen
- T-haraldson
- T-haraldssen
- T-haraldsson
- T-hatcher
- T-haulow
- T-hea
- T-heatercafeen
- T-heisen
- T-hemsen
- T-heodor
- T-herese
- T-hom
- T-homas
- T-homason

**[Words ending with "th"](http://ord-som-ender.finn-et-ord.net/ord-som-slutter-th.html):**
- Aarset-h
- Arnset-h
- Bayreut-h
- Bratset-h
- Dalset-h
- Dulut-h
- Elisabet-h
- Elizabet-h
- Elset-h
- Espeset-h
- Furuset-h
- Grundset-h
- Heat-h
- Hjort-h
- Hofset-h
- Holt-h
- Høiset-h
- Judit-h
- Kennet-h
- Langset-h
- Lent-h
- Lindset-h
- Lisbet-h
- Løset-h
- Margaret-h
- Meinset-h
- Myrset-h
- Nordset-h
- Nort-h
- NT-H
- Opset-h
- Pert-h
- Portsmout-h
- Queset-h
- Riset-h

I think it works well for words with "th" in the middle, but it's a bit awkward for words that start and end with "th". In general though, "th" seems to be a breaking point that should be considered?

**Comment by matskober** [comment]
Is there any good way to hyphenate a four letter word? I would have thought there was a rule saying never to to hyphenate anything with less than five letters; could that be applied? 

Also: Is it possible to define a algoritme that makes sure hyphenation only takes place if there is an actual benefit by doing so, e.g. that the hyphenation 'gains space', so that the paragraf in witch it occurs, uses less lines.

**Comment by KariRudjord** [comment]
Dublett
