### ISSUE TITLE
Toc heading "Innhold" on an otherwise empty page

### ISSUE THREAD

**Issue by matskober** [nlbdev/pipeline#151]
job 1726

If no hx in the book, PIP generates an empty toc.
[results.zip](https://github.com/nlbdev/pipeline/files/1509627/results.zip)

**Comment by josteinaj** [comment]
Do we want to add a text in the about page saying that there are no headlines in this book? Or do we want to generate headlines maybe?

**Comment by matskober** [comment]
To add a text in 'Om boka' sounds good, but also skip the word/heading
'Innhold'?

**Comment by KariRudjord** [comment]
I think a text in Om boka is not neccesary. Om boka will not be read if there is  too much information there, and books without headlines is quite normal.

I only want that when no TOC is present, the TOC page with headline is removed.

**Comment by josteinaj** [comment]
Ok.

@bertfrees could you have a look at this when you have time?

**Comment by bertfrees** [comment]
Ok I'll have a look. I'm not sure I can fix this with CSS, but I can always pass a variable "no-headings" from XProc to SCSS.

**Comment by KariRudjord** [comment]
Dublett.
