### ISSUE TITLE
Improve english hyphenation

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#154]
Job 1766 gets hyphenation like this
t-hemes
fis-herman
t-hat

**Comment by bertfrees** [comment]
Is this with Norwegian (force-norwegian) or English braille rules?

**Comment by KariRudjord** [comment]
The whole book is marked xml lang en so I think english braille rules

**Comment by bertfrees** [comment]
The "force-norwegian" option is important here.

**Comment by KariRudjord** [comment]
I thought that if the whole book is marked en it would be turned off? Maybe I'm wrong? OK, its written in the GUI, it always use norwegin, yes.

**Comment by bertfrees** [comment]
That's not the case at the moment. So this issue is probably a duplicate of https://github.com/nlbdev/pipeline/issues/152.

**Comment by matskober** [comment]
I ran an English book here the other day, unchecking "alltid Norsk", but
the t-hat was present there as well ...

**Comment by josteinaj** [comment]
Closing as duplicate of #152.

**Comment by bertfrees** [comment]
But what about what Mats said?

**Comment by josteinaj** [comment]
Oh, I see. Hyphenation also happens for english books even if force-norwegian is false?
