### ISSUE TITLE
Rapport for tabeller

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#156]
Kanskje alle tabeller bør vises i et dokument, tilsvarende sånn som bilder vises i ACE-rapporten. Også gjerne vise leserekkefølge på en eller annen måte.

**Comment by matskober** [comment]
Seems like a briljant idea with tables gather in a separat document. In
books with frequent and complex tables it might even be something to
consider in braille, to keep the tables in separat volumes. It would keep
the "text flow" better in the book (and thereby keep those who believe
tables in Braille to be bullshit happy)  - and it might also be possible to
render the tables in a dedicated format , e.g. with longer lines or
someting, to improve the readability of the braille tables.

**Comment by josteinaj** [comment]
@matskober jeg byttet til norsk. Dette er ikke del av punktprosjektet men del av prosjekt der vi definerer egen NLB-standard for oppmerking. Gjerne lag egne kort på de punktspesifikke forslagene dine som innspill til punktprosjektet.

**Comment by josteinaj** [comment]
Flyttet til https://github.com/nlbdev/nlbpub/issues/3
