### ISSUE TITLE
Sami alphabet: á

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#159]
In the Sami braille alphabet, á should be ⠷ (12356), but in the Norse, Icelandic, Danish and Norwegian alphabets, á should be ⠡ (16). Currently we're using the Sami version for all alphabets.

@KariRudjord maybe we should use ⠡ (16) instead of ⠷ (12356) as default?

---

**line 51**:
- Input:    '`a á b d ð e f g h i í j k l m n o ó p r s t u ú v y ý æ ö`'
- Expected: '`⠁ ⠡ ⠃ ⠙ ⠱ ⠑ ⠋ ⠛ ⠓ ⠊ ⠣ ⠚ ⠅ ⠇ ⠍ ⠝ ⠕ ⠹ ⠏ ⠗ ⠎ ⠞ ⠥ ⠻ ⠧ ⠽ ⠯ ⠜ ⠪`' (length 57)
- Received: '`⠁ ⠷ ⠃ ⠙ ⠱ ⠑ ⠋ ⠛ ⠓ ⠊ ⠣ ⠚ ⠅ ⠇ ⠍ ⠝ ⠕ ⠹ ⠏ ⠗ ⠎ ⠞ ⠥ ⠻ ⠧ ⠽ ⠯ ⠜ ⠪`' (length 57)
- Diff:     Expected '`⠡`' but received '`⠷`' in index 2

---

**line 613**:
- Input:    '`Dvořák`'
- Expected: '`⠠⠙⠧⠕⠈⠗⠡⠅`' (length 8)
- Received: '`⠠⠙⠧⠕⠈⠗⠷⠅`' (length 8)
- Diff:     Expected '`⠡`' but received '`⠷`' in index 6

---

**line 620**:
- Input:    '`Málaga`'
- Expected: '`⠠⠍⠡⠇⠁⠛⠁`' (length 7)
- Received: '`⠠⠍⠷⠇⠁⠛⠁`' (length 7)
- Diff:     Expected '`⠡`' but received '`⠷`' in index 2

---

**line 633**:
- Input:    '`sápmelaš`'
- Expected: '`⠎⠡⠏⠍⠑⠇⠁⠈⠎`' (length 9)
- Received: '`⠎⠷⠏⠍⠑⠇⠁⠱`' (length 8)
- Diff:     Expected '`⠡`' but received '`⠷`' in index 1

---

**line 646**:
- Input:    '`Bláalóniđ`'
- Expected: '`⠠⠃⠇⠡⠁⠇⠹⠝⠊⠹`' (length 10)
- Received: '`⠠⠃⠇⠷⠁⠇⠹⠝⠊⠹`' (length 10)
- Diff:     Expected '`⠡`' but received '`⠷`' in index 3

**Comment by KariRudjord** [comment]
Yes, use 16 insted of 12356 as default for á.

**Comment by josteinaj** [comment]
Great, I'll change that.

There's also a couple of characters for Norse and Icelandic that fails. We can't fix these unless we create separate Norse and Icelandic tables, but I'm listing them here for reference:

**Norse**:
Input: é þ oe
Expected: ⠮ ⠫ ⠬
Received: ⠿ ⠔⠞ ⠕⠑

**Icelandic**:
Input: é þ
Expected: ⠮ ⠫
Received: ⠿ ⠔⠞

**Comment by josteinaj** [comment]
@KariRudjord In Norwegian, characters with a circumflex or reverse circumflex should be prefixed with ⠨ (dot 46). So a š should be ⠨⠎ (46-234). The š is defined in the Sami alphabet to be ⠱ (156). Should we go for the Sami version in this case? Always use ⠱ (156) for š?

**Comment by josteinaj** [comment]
Actually, š is defined as ⠱ (156) already it seems. It's just a test that fails:

Input: `sápmelaš`
Expected: `⠎⠡⠏⠍⠑⠇⠁⠈⠎`

I'll change the expected output to be: `⠎⠡⠏⠍⠑⠇⠁⠱`

**Comment by josteinaj** [comment]
Also adding Œœ ("latin ligature oe") as the norse "oe" sign (hoping that's correct). Adding as ⠬ (dot 346).

**Comment by KariRudjord** [comment]
Norse: Input: é þ oe Expected: ⠮ ⠫ ⠬ Received: ⠿ ⠔⠞ ⠕⠑ OK as received.
Icelandic: Input: é þ Expected: ⠮ ⠫ Received: ⠿ ⠔⠞). OK as received.
