### ISSUE TITLE
Footnotes - minor layout change

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#162]
1. When notes are placed on bottom of the page, it should start on cell 5 (not 3) to be clear divided from ordinary text.

2. If it is easy to put into CSS, I would also like a boarder (36) placed before the notes to make a clear separation from ordinary text.

3. When choosing Notes on bottom of page in GUI, but actually some notes are too large, so the fallback mechanism is used - in this case everything is OK except the fact that the notes put in the back of the volume doesn't have a headline (like there are with regular option Notes in end of volume). The same layout would be nice also when fallback so that Notes always have the same layout.

**Comment by bertfrees** [comment]
1. I don't think this is possible at the moment. When choosing Notes on bottom of page and the fallback mechanism is activated, I can not make change the layout of the notes itself. Only the destination is changed. So the notes will still start in cell 5 if they are moved to the end of the volume.

2. Yes, creating a border is easy. I've updated the CSS.

3. I fixed it.

**Comment by KariRudjord** [comment]
2 and 3 not working, but no high priority. We can look at it later if needed.

**Comment by bertfrees** [comment]
@KariRudjord Are you sure it was deployed?

**Comment by KariRudjord** [comment]
Sorry, I don't understand the word deployed (implemented?). I chose Notes on bottom of page, but no boarder is to see:
![fotnote](https://user-images.githubusercontent.com/12409918/34564522-418e4d06-f157-11e7-867f-39a745010264.PNG)

**Comment by bertfrees** [comment]
"Deployed" means that Jostein has installed the feature on your test server. But since this issue is still in the "Ready for deployment" column I assume it is not installed yet.

**Comment by KariRudjord** [comment]
And for 3., with fallback when notes are placed back in volume, it apperas like this:
![fotnote2](https://user-images.githubusercontent.com/12409918/34564654-d38ed2c0-f157-11e7-8373-ca369eb5ee86.PNG)

**Comment by KariRudjord** [comment]
OK. I thouht it was in ready for test, but I see now that it was in unsorted elements Q1-2018 :-)

**Comment by KariRudjord** [comment]
Works.
