### ISSUE TITLE
Volume break - small volumes

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#166]
I tried a study book (559880) with lots of things in frontmatter, preface etc, and it worked fine. But two of the volumes contains very few pages. 

Vol. 6 is 30 pages and stops inside av level2. 

Vol. 14 is 24 pages and ends on the end of a part two. 

I don't understand why the volumes gets so small. Its best to fill out volumes as much as possible.

**Comment by josteinaj** [comment]
It always splits at the beginning of a part. Could that be the problem?

**Comment by KariRudjord** [comment]
No parts in this book.

**Comment by bertfrees** [comment]
Shouldn't this be retested first?

**Comment by josteinaj** [comment]
Ok, sure.

**Comment by KariRudjord** [comment]
I think this is good. A bit small volumes sometimes, but practical that volumes contain whole chapters.
