### ISSUE TITLE
TOC - line improvement

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#169]
Sometimes text in TOC is placed in the "page number column", and sometimes a line with only dots follows. Is it possible to avoid this? Example from DTBook as input. Most important to fix this in EPUB as input

![skjermbilde](https://user-images.githubusercontent.com/12409918/35001918-4cb934ee-fae8-11e7-9c03-f396e57ef75d.PNG)

**Comment by bertfrees** [comment]
SBS has the same requirement: https://github.com/sbsdev/pipeline-mod-sbs/issues/51

**Comment by bertfrees** [comment]
See https://github.com/braillespecs/braille-css/issues/21#issuecomment-385034548

**Comment by bertfrees** [comment]
The first part of the issue, namely that no text should be placed in the page number column, is fixed and can be tested.

The second part of the problem, namely that there should be no lines with only leader dots and a page number, is not fixed yet.

**Comment by KariRudjord** [comment]
First part tested and works.
Second part less important. (And have to wait some other issue is fixed, recording to Bert.)

**Comment by josteinaj** [comment]
@KariRudjord Great!

@bertfrees Shall we move this back to "Needs automated test" or "Needs development"?

**Comment by bertfrees** [comment]
Needs development.
