### ISSUE TITLE
Improve performance of Pipeline

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#17]
_From @bertfrees on November 17, 2016 12:13_

This is just a reference to https://github.com/snaekobbi/issues/issues/28. This way I'm adding the issue to NLB's to-do list.

The system must be able to handle several productions a day, including repeating productions that need more adjustments in source file.

_Copied from original issue: nlbdev/pipeline-mod-nlb#55_

**Comment by josteinaj** [comment]
Speed is much better now so we're marking this as *done*.

**Comment by bertfrees** [comment]
I haven't pushed the "shift-id" fix yet by the way.

**Comment by josteinaj** [comment]
Ok. Its a lot better already so the shift-id fix is maybe not a high priority, although it would of course be nice to have it.

**Comment by josteinaj** [comment]
Ok. Its a lot better already so the shift-id fix is maybe not a high priority, although it would of course be nice to have it.

**Comment by josteinaj** [comment]
I don't know if the shift-id fix is included or not but we're very happy with the performance improvements so I'm closing this issue.

**Comment by bertfrees** [comment]
It's not included.

**Comment by josteinaj** [comment]
Ok, good to know.
