### ISSUE TITLE
Fraction and mixed numbers (Brøk og blandede tall)

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#170]
Liv Kristin has tested, and it its wrong translation. 
11/2 and 1/2 (1/4 and 1/8 also needs a check)
1 1/2 PIP result: 3456-1 6-16-34-126
Should be 3456-1-3456-1-34-12

1/2 shall be 3456-1-34-12

Håndboka kap. 8.3

**Comment by KariRudjord** [comment]
When using unicode sign, fractions are not rendered right. These need to be put into Liblouis:
Maybe something you can fix, @usama49 ?

&#x00BD;  3456-1-34-3456-12 (numbersign1/numbersign2)
&#188;  3456-1-34-3456-145
&#190;   3456-14-34-3456-145
&#8531;  3456-1-34-3456-14
&#8532;  3456-12-34-3456-14
&#8530;  3456-1-34-3456-245
&#8533;  3456-1-34-3456-15
&#8534;  3456-12-34-3456-15
&#8535;  3456-14-34-3456-15
&#8536;  3456-145-34-3456-15
&#8537;  3456-1-34-3456-124
&#8538;  3456-15-34-3456-124
&#8528;  3456-1-34-3456-1245
&#8539;  3456-1-34-3456-125
&#8540;  3456-14-34-3456-125
&#8541;  3456-15-34-3456-125
&#8542;  3456-1245-34-3456-125
&#8529;  3456-1-34-3456-24
&#8585;  3456-245-34-3456-14

http://unicodefractions.com/

**Comment by bertfrees** [comment]
In the table ½ is currently mapped to 6-16-34-126. Any idea where that could come from? (This rule has been in the table from the beginning of SVN history. Either Leon Ungier or Lars Bjørndal has put it in there.)

**Comment by josteinaj** [comment]
I don't know.

In "Håndbok i litterær punktskrift", which defines how to write fractions, it is as Kari describes it.

**Comment by KariRudjord** [comment]
There's one little missing dot to make this perfect, and it's my fault who has forgot the 1 in 10 at the end.
⅒ 3456-1-34-3456-245 should be like this:
⅒ 3456-1-34-3456-1-245

**Comment by bertfrees** [comment]
Fixed

**Comment by KariRudjord** [comment]
Works.
