### ISSUE TITLE
Consider changing focus from EPUB to HTML

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#171]
Our master format is now a EPUB with a single HTML file inside. It's pretty much the same as our current EPUBs, but with all the content documents merged into one. It would probably make sense to focus on getting a conversion from that HTML file to PEF working instead of having to consider multiple HTML input files. It would also make it easier to create a test suite as we could mostly just copy the DTBook tests and rename the elements.

@KariRudjord I think we should have a meeting about this when we get the time.

**Comment by matskober** [comment]
I thought PIP already merged all the htmls in the EPUB into one html, "on
the run", so how does this differ?

Mats

**Comment by josteinaj** [comment]
Yes it merges them into one HTML. However, it doesn't merge in quite the same way as the nordic migrator does. For instance, this is how the braille script represents multiple HTML documents:

```html
<html>
<head>...</head>
<body epub:type="cover">...</body>
<body epub:type="part">...</body>
<body epub:type="chapter">...</body>
<body epub:type="chapter">...</body>
<body epub:type="part">...</body>
<body epub:type="chapter">...</body>
<body epub:type="chapter">...</body>
<body epub:type="appendix">...</body>
</html>
```

...and this is how the single-HTML file is represented when converting the epub to html using the nordic migrator:

```html
<html>
<head>...</head>
<body>
    <section epub:type="cover">...</section>
    <section epub:type="part">
        ...
        <section epub:type="chapter">...</section>
        <section epub:type="chapter">...</section>
    </section>
    <section epub:type="part">
        ...
        <section epub:type="chapter">...</section>
        <section epub:type="chapter">...</section>
    </section>
    <section epub:type="appendix">...</section>
</body>
</html>
```

The second one is what we will use as our master format, so unless we split the HTML files, we will soon use a single HTML file as input anyway, whether or not we package it as an EPUB. So maybe we don't need to maintain the CSS for both the multi-HTML representation as well as the single-HTML representation...

**Comment by KariRudjord** [comment]
Maybe this is something to consider for text to speech as well?
