### ISSUE TITLE
EPUB/HTML as input - TOC layout improvement

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#172]
TOC with EPUB as input needs adjustmenst:
- standard should be 2 in depth of TOC in GUI
- From text to pagenumber in endtries in TOC there should be a line of (3) and the page number should be right-justified
⠀⠀⠠⠋⠕⠗⠕⠗⠙⠀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠀⠼⠛⠀
⠀⠀⠠⠊⠝⠝⠇⠑⠙⠝⠊⠝⠛⠀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠀⠼⠁⠁⠀
-

**Comment by josteinaj** [comment]
@KariRudjord your example looks right-justified already?

**Comment by KariRudjord** [comment]
Yes, the example is a DTBook-production. With EPUB it gets like this:
⠀⠼⠁⠀⠠⠄⠠⠊⠝⠝⠇⠑⠙⠝⠊⠝⠛⠠⠄⠀⠼⠁⠁⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠼⠁⠀⠠⠍⠊⠛⠗⠁⠎⠚⠕⠝⠀⠅⠕⠝⠞⠗⠁⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠊⠍⠍⠕⠃⠊⠇⠊⠞⠑⠞⠀⠼⠁⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠼⠃⠀⠠⠍⠊⠛⠗⠁⠎⠚⠕⠝⠀⠋⠗⠁⠀⠑⠞⠀⠋⠁⠛⠇⠊⠛⠀

**Comment by josteinaj** [comment]
Ok, thanks.

**Comment by KariRudjord** [comment]
Works.

**Comment by matskober** [comment]
HI,
See JOB 2496

The TOC looks fine, but it appears two times.

MAts

**Comment by josteinaj** [comment]
@matskober I see you're using the epub-to-pef script, maybe this is only a problem when using EPUB as input?

edit: I tested now and it seems to be an issue when using epub as input. I'm creating a separate issue for it: #186

**Comment by KariRudjord** [comment]
Have not seen the problem with HTML as input. Have seen several things that don't work with the EPUB to PEF. But we are not going to use that script anyway.

**Comment by matskober** [comment]
No. I have not checked with other than epub-to-pef
