### ISSUE TITLE
EPUB/HTML as input - TOC missing

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#175]
For 562416 TOC is present with DTBook input but absent with NLBPUB as input. I can't figure why.
Job 2253

**Comment by josteinaj** [comment]
See: https://github.com/nlbdev/pipeline/commit/85f443e5116b5cbbb417fe8683966215194b40a4#diff-bf122ae92813a58b8a75b98bf09ba992R951

**Comment by josteinaj** [comment]
Replaced by checklist item in #23
