### ISSUE TITLE
Move preprocessing steps out of the system

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#176]
These:

- [pre-processing.xpl](https://github.com/nlbdev/pipeline/blob/a4f175c16e701bdff662f082eff2c2e57032db36/modules/nlb/book-to-pef/src/main/resources/xml/pre-processing.xpl)
- [pre-processing.xsl](https://github.com/nlbdev/pipeline/blob/a4f175c16e701bdff662f082eff2c2e57032db36/modules/nlb/book-to-pef/src/main/resources/xml/pre-processing.xsl)
- [pre-processing-epub.xsl](https://github.com/nlbdev/pipeline/blob/a4f175c16e701bdff662f082eff2c2e57032db36/modules/nlb/book-to-pef/src/main/resources/xml/pre-processing-epub.xsl)

...should be moved here:

[xslt/prepare-for-braille/prepare-for-braille.xsl](https://github.com/nlbdev/produksjonssystem/blob/9929f5f3631d8a2795072119924bd1da4a133f97/xslt/prepare-for-braille/prepare-for-braille.xsl) (as part of [NLBs production system](https://github.com/nlbdev/produksjonssystem))

**Comment by bertfrees** [comment]
Maybe part of what's in the pre-processing makes sense to keep here because it's pure styling. Don't know.

**Comment by josteinaj** [comment]
It's easier for us to maintain a pre-processing step outside of the Pipeline 2 system. We have other XSLTs for pre-processing books for narration, TTS and e-books, so it fits well into our production system. We may want to reuse some pre-processing steps across production lines as well, I don't know yet. The pre-processed books will then be available for the producer to inspect before manually producing them through the GUI or Web UI, as well as being used as input for automated production with Pipeline 2.

**Comment by josteinaj** [comment]
I think this is out of scope. We might copy some of the rules from `pre-processing.xsl` to our production system in the future, but that's a separate effort.
