### ISSUE TITLE
Capital sign in acronyms with mixed captials and small letters

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#177]
Statped:
when acronyms are mixed capitals and small letters the capital sign should be present in front of each capital like this:
KrFU: ⠠⠅⠗⠠⠋⠠⠥

Not like this:
⠠⠅⠗⠠⠠⠋⠥

**Comment by josteinaj** [comment]
@bertfrees is this an issue we can move to the liblouis repo? It sounds like it's not specific to Pipeline 2?

**Comment by bertfrees** [comment]
Yes, I think we can. Can you first check if there is already a test for this in https://github.com/liblouis/liblouis/blob/master/tests/braille-specs/no_harness.yaml?

**Comment by josteinaj** [comment]
There's this test:

https://github.com/liblouis/liblouis/blob/1ed46203ad67ee3b49287e5c6a49eec06951786d/tests/braille-specs/no_harness.yaml#L253-L256

```
  -
    - DTBook NBfU
    - ⠠⠙⠠⠞⠠⠃⠕⠕⠅ ⠠⠝⠠⠃⠋⠠⠥
    - {xfail: true}
```

But I think maybe there should be a test with a word that ends with multiple captal letters, to be completely sure.

So I added what is described by Kari as a test in this PR:
https://github.com/liblouis/liblouis/pull/1429

I'm closing this issue.
