### ISSUE TITLE
Right/left arrow

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#179]
Statped
Rightvards arrow U+2192 &#8594;  (25-5)
Leftvards arrow U+2190 &#8592;  (5-25)

**Comment by bertfrees** [comment]
Does this mean "-->" and "<--" should also be translated like this?

**Comment by KariRudjord** [comment]
No, my mistake.

**Comment by josteinaj** [comment]
@KariRudjord ok, then this is ready to be tested.

**Comment by bertfrees** [comment]
> > Does this mean "-->" and "<--" should also be translated like this?
> 
> No, my mistake.

Well I implemented it anyway: https://github.com/nlbdev/pipeline/commit/ba5149481ad9fcc87baf650281e35824bc55a938#diff-c426ae625eef089f0c7ef9a1b098007aR208

**Comment by josteinaj** [comment]
Hmm, could it be problematic in some cases? At least if there's a book about HTML, but maybe not an issue in other cases...

Currently:
`→` and `-->`: `⠒⠐`
`←` and `<--`:`⠐⠒`

Without `-->`/`<--` rule:
`-->`: `⠤⠤⠕⠂`
`<--`:`⠪⠄⠤⠤`

@KariRudjord what do you think? Should `-->` and `<--` be converted to `→` and `←` or not?

**Comment by KariRudjord** [comment]
It could get in conflict with some xml-expressions, according to Per. So I think we skip the -->

**Comment by josteinaj** [comment]
Ok, I'll change it.

**Comment by josteinaj** [comment]
Reverted `<--` and `-->` in: e7554f321da8e89cdf0f6a2a616b5aa9aeb3ed18

**Comment by KariRudjord** [comment]
Works.

**Comment by josteinaj** [comment]
I haven't installed it yet though, but ok :).
