### ISSUE TITLE
Improve stability of Pipeline

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#18]
_From @bertfrees on November 17, 2016 12:34_

The system must be reliable.

This is just a reference to https://github.com/daisy/pipeline-mod-braille/issues/135. This way I'm adding the issue to NLB's to-do list.

_Copied from original issue: nlbdev/pipeline-mod-nlb#56_

**Comment by bertfrees** [comment]
@josteinaj Have you noticed any improvements since updating to the latest Pipeline?

**Comment by josteinaj** [comment]
Yes I believe so. Or at least it hasn't crashed yet. Previously we had to
do so a couple of times a day I remember.

Jostein

30. jun. 2017 18:33 skrev "Bert Frees" <notifications@github.com>:

**Comment by josteinaj** [comment]
The system seems quite stable, from the testing we've done over the last 8 days. For this sprint we're quite happy with the stability so I'm closing this.
