### ISSUE TITLE
Change in notation <prodnote>

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#184]
From OUP 25.4.18: The notation for producers comment (`<prodnote>`) is changed to 56-3 before and 6-23 after the comment.

This must be changed in Liblouis (today it's 12356 before and 23456 after.)

**Comment by bertfrees** [comment]
This is not done in Liblouis right now but in CSS.
https://github.com/nlbdev/pipeline/blob/37af0421a8dc7624e9f1e1dfecf963ab9d006e09/modules/nlb/book-to-pef/src/main/resources/css/nlb-default.scss#L609-L617

**Comment by KariRudjord** [comment]
Works.
