### ISSUE TITLE
Hyphen improvement

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#201]
Dictionary for hyphen: Jostein has implemented somet new things after communication with Knut Arne Bjørndal (Bibelen)

After this the hyphenation is working much better, but still with some bad mistakes.

Waiting for Sensus/Lars to respond on our request for help with this. I have not heard from him in 1-2 weeks. And I haven't updated him with the latest news. Maybe you have, @josteinaj ?

**Comment by josteinaj** [comment]
No, I don't have any more information and I haven't updated them.

**Comment by KariRudjord** [comment]
We've overlooked the hyphenation one more time. Mari and I think it is sufficient the way it is now.

Sensus/Lars has offered to design a solution that handle words that are bad hyphenated. His offer has no concrete description og budget. We have declined this offer for now. Maybe something Statped might want later?
