### ISSUE TITLE
Strange bug in "Om boka!

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#205]
For 120195 there is a strange bug in "Om boka" that I have never seen before: Capital sign in the first to sentences becomes number sign:

#17TALL SIDER3 #568
--
#387;A SKAL IKKE RETURNE-
RES'

In other books it is like this:

,ANTALL SIDER3 #178
--
,BOKA SKAL IKKE RETURNERES'

**Comment by josteinaj** [comment]
In July I added some simple post-processing to the preview:

- `>` becomes `Æ`
- `[` becomes `Ø`
- `*` becomes `Å`
- anything that follows a `#` (up until the next space or newline) is translated to numbers:
  - `1` becomes `,`
  - `'` becomes `.`
  - `ABCDEFGHIJ` becomes `1234567890`
- words that start with `,,` becomes uppercase
- letters that are preceded by `,` becomes uppercase
- all other letters become lowercase

All this is just to improve readability of the preview and does not affect the PEF itself.

Is this a problem in the PEF as well, or just in the preview?

**Comment by KariRudjord** [comment]
Was not able to recreate the bug.
