### ISSUE TITLE
Basic support for combining marks

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#21]
_From @josteinaj on November 17, 2016 12:58_

Due to limitations in liblouis, combining marks are not supported. See: https://github.com/nlbdev/pipeline/issues/4.

However, as a more basic solution, we can replace characters with combining marks with combining mark-less equivalents:
- `å` (U+61 U+030A) has the equivalent character `å` (U+E5)
- `e̊` (U+65CC U+8A) can be rewritten into either `e˚`, `e` or `⠈e`

_Copied from original issue: nlbdev/pipeline-mod-nlb#59_

**Comment by bertfrees** [comment]
It doesn't look like Liblouis will have native support for combining marks anytime soon. What about a preprocessing step `px:nfc`? It can be implemented with [java.text.Normalizer](https://docs.oracle.com/javase/7/docs/api/java/text/Normalizer.html). For the cases where there exists no single codepoint for a character, I suggest we implement it in the Liblouis table somehow.

**Comment by josteinaj** [comment]
Yes, `px:nfc` sounds perfect. Can I assign this to you?

**Comment by bertfrees** [comment]
Sure, if you like. What about the Liblouis part? Do we have some tests for that?

**Comment by josteinaj** [comment]
There are some diacritics in the liblouis tests, but I don't think they use combining marks anywhere (see also #4 which is about liblouis support). We could have a xprocspec test for combining marks in the nlb scripts.

**Comment by josteinaj** [comment]
`px:nfc` would probably be useful for other scripts as well. So it would probably go in `pipeline-common-utils`?

**Comment by bertfrees** [comment]
Yes we should have a test in the NLB module (Java/XSpec/XProcSpec), but also a Liblouis test I think:
- list some diacritic characters as NFC that are handled correctly by Liblouis
- list some diacritic characters that don't have a single codepoint representation and are handled by Liblouis
- list some diacritic characters using combining marks that also have a NFC representation, and do not have to be handled by Liblouis (can have xfail flag)

>`px:nfc` would probably be useful for other scripts as well

Yeah, maybe. Ok I'll put it in common-utils.

**Comment by bertfrees** [comment]
Done. I've put px:nfc in mod-nlb for now because it depends on a class from mod-braille. We can move it to common-utils when https://github.com/daisy/pipeline-scripts/issues/123 is done because for that issue I have moved the class I depend on to the framework.

**Comment by bertfrees** [comment]
You might want to check the grade 1 translation of letters with diacritics. Liblouis has the following rules:

```
noletsign å
noletsign Å
noletsign à
noletsign á
```

This means that the characters above will not get a dot 56 in front of them when they appear alone. Does that make sense? Are there more cases like these?

**Comment by josteinaj** [comment]
For å and Å it makes sense. Not sure about à and á.

@KariRudjord what do you think?
