### ISSUE TITLE
Update to Pipeline 2 v1.12

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#220]
I've updated the system to use the v1.12 assembly (which is needed for the latest webui, which is needed to be run properly in Docker, which we need to be able to use a newer Java version, etc.), but still use the SNAPSHOT versions of the braille modules used on our version of the system. The system builds fine, but when I run it, I get errors.

The tests probably run using the previous version of the framework. I've tried updating the version references in the POMs, but I couldn't get it working. There seems to have been a lot of changes.

@bertfrees could you have a look at this?

~See also #221 (to keep in mind when updating)~

**Comment by bertfrees** [comment]
I'll have a look.

**Comment by bertfrees** [comment]
OK done.

**Comment by josteinaj** [comment]
Thanks! Looks good.
