### ISSUE TITLE
Unable to parse URL CSS style

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#222]
## Instructions to reproduce

**build and run the system:**
```bash
docker build . -t nlb-pipeline
docker run --network=host --rm -it nlb-pipeline
```

**run the webui:**
```bash
docker run --network=host --rm -it daisyorg/pipeline-webui
```

### HTML to PEF (generic script)

- Upload src/test/resources/single-html/C00000.xhtml (from the nordic migrator project)
- Run the script "HTML to PEF"
- Error: "Attempt to set parameter but there's no parameter port."
- Log: [job-11.log](https://github.com/nlbdev/pipeline/files/3178209/job-11.log)

### HTML to PEF (NLB script)

- Upload src/test/resources/single-html/C00000.xhtml (from the nordic migrator project)
- Run the script "HTML to PEF (NLB)"
- Error: "Unable to parse URL CSS style"
- Log: [job-12.log](https://github.com/nlbdev/pipeline/files/3178206/job-12.log)

### EPUB 3 to PEF (NLB script)

- Upload src/test/resources/C00000.epub (from the nordic migrator project)
- Run the script "HTML to PEF (NLB)"
- Error: "Unable to parse URL CSS style"
- Log: [job-13.log](https://github.com/nlbdev/pipeline/files/3178216/job-13.log)

@bertfrees do you think this is something you have time to look at at some point?

**Comment by bertfrees** [comment]
Sure. Just let me know what the priority is compared to the other issues.

**Comment by josteinaj** [comment]
Great.

This is blocking the other issues. I need to get the system running again, and in Docker, so that Kari can start testing the newest version again.

The nordic migrator doesn't work either (some dependency issue):
```
org.apache.felix.log.LogException: org.osgi.framework.BundleException: Unable to resolve org.daisy.pipeline.modules.nordic-epub3-dtbook-migrator [147](R 147.0): missing requirement [org.daisy.pipeline.modules.nordic-epub3-dtbook-migrator [147](R 147.0)] osgi.wiring.package; (&(osgi.wiring.package=org.daisy.pipeline.script)(version>=3.2.0)(!(version>=4.0.0))) Unresolved requirements: [[org.daisy.pipeline.modules.nordic-epub3-dtbook-migrator [147](R 147.0)] osgi.wiring.package; (&(osgi.wiring.package=org.daisy.pipeline.script)(version>=3.2.0)(!(version>=4.0.0)))]
```

**Comment by bertfrees** [comment]
Is it all committed on the nlb branch of the super project?

**Comment by bertfrees** [comment]
I fixed the generic script (Attempt to set parameter but there's no parameter port), but I couldn't reproduce the other error. (But note that I haven't tried the Docker image.)

**Comment by bertfrees** [comment]
It looks like it's the line `@charset "UTF-8"` (which is automatically added when compiling nlb-default.scss to CSS) is what is causing the error. It only happens in the Docker container, so maybe it has something to do with the "Set locales" section in the Dockerfile. Anyway, I fixed a bug in jStyleParser which should fix the error.

**Comment by bertfrees** [comment]
The nordic migrator does not work because you aren't using the latest version.

```diff
modified   assembly/pom.xml
@@ -145,7 +145,7 @@
       <dependency>
         <groupId>org.daisy.pipeline.modules</groupId>
         <artifactId>nordic-epub3-dtbook-migrator</artifactId>
-        <version>1.3.0</version>
+        <version>1.4.1-SNAPSHOT</version>
       </dependency>
     </dependencies>
   </dependencyManagement>
```

**Comment by josteinaj** [comment]
Thanks! I'll try again now.

**Comment by josteinaj** [comment]
Works. Now that I have the system running in a Docker container, I'll be configuring a new test server for internal (and probably external) testing very soon.
