### ISSUE TITLE
Improved HTML support

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#23]
_From @josteinaj on November 17, 2016 13:19_

Initial EPUB 3 support was added in #35.

Further work is needed. We need to test that the script works on our books and that we are satisfied with the output. This might entail work on SCSS, preprocessing and postprocessing steps, as well as improvements to the XProc/XSLT implementation of the script (either NLB-specific or generic).

_Copied from original issue: nlbdev/pipeline-mod-nlb#61_

---

When these tests are fixed, the HTML support will be as good as the DTBook support, and then we can close this issue:

- [x] [test_html-to-pef.xprocspec:](https://github.com/nlbdev/pipeline/blob/999e94f5280c83739801a7a38ea0f8232a2ceaed/modules/nlb/book-to-pef/src/test/xprocspec/test_html-to-pef.xprocspec#L9)
- [x] [test_html-to-pef_generated-content.xprocspec: 2 volumes](https://github.com/nlbdev/pipeline/blob/999e94f5280c83739801a7a38ea0f8232a2ceaed/modules/nlb/book-to-pef/src/test/xprocspec/test_html-to-pef_generated-content.xprocspec#L861)
- [x] [test_html-to-pef_generated-content.xprocspec: multiple volumes](https://github.com/nlbdev/pipeline/blob/999e94f5280c83739801a7a38ea0f8232a2ceaed/modules/nlb/book-to-pef/src/test/xprocspec/test_html-to-pef_generated-content.xprocspec#L1408)
- [x] [test_html-to-pef_generated-content.xprocspec: toc](https://github.com/nlbdev/pipeline/blob/999e94f5280c83739801a7a38ea0f8232a2ceaed/modules/nlb/book-to-pef/src/test/xprocspec/test_html-to-pef_generated-content.xprocspec#L951)
- [x] [test_html-to-pef_volume-breaking.xprocspec: Content at start of part (or chapter) should be in same volume as first descendant chapter (or subchapter) - short level1, long level2](https://github.com/nlbdev/pipeline/blob/999e94f5280c83739801a7a38ea0f8232a2ceaed/modules/nlb/book-to-pef/src/test/xprocspec/test_html-to-pef_volume-breaking.xprocspec#L915)
- [x] [test_html-to-pef_volume-breaking.xprocspec: with parts: fit small chapters in same volume, medium chapters in separate volumes, and big chapters in multiple volumes](https://github.com/nlbdev/pipeline/blob/999e94f5280c83739801a7a38ea0f8232a2ceaed/modules/nlb/book-to-pef/src/test/xprocspec/test_html-to-pef_volume-breaking.xprocspec#L189)
- [x] [test_html-to-pef_volume-breaking.xprocspec: with parts: parts will be top level splitting points](https://github.com/nlbdev/pipeline/blob/999e94f5280c83739801a7a38ea0f8232a2ceaed/modules/nlb/book-to-pef/src/test/xprocspec/test_html-to-pef_volume-breaking.xprocspec#L132)
- [x] [test_html-to-pef_notes.xprocspec: Automatic numbering of notes](https://github.com/nlbdev/pipeline/blob/999e94f5280c83739801a7a38ea0f8232a2ceaed/modules/nlb/book-to-pef/src/test/xprocspec/test_html-to-pef_notes.xprocspec#L9)
- [x] [test_html-to-pef_notes.xprocspec: Footnotes](https://github.com/nlbdev/pipeline/blob/999e94f5280c83739801a7a38ea0f8232a2ceaed/modules/nlb/book-to-pef/src/test/xprocspec/test_html-to-pef_notes.xprocspec#L335)
- [x] [test_html-to-pef_notes.xprocspec: Notes at end of book](https://github.com/nlbdev/pipeline/blob/999e94f5280c83739801a7a38ea0f8232a2ceaed/modules/nlb/book-to-pef/src/test/xprocspec/test_html-to-pef_notes.xprocspec#L438)
- [x] [test_html-to-pef_notes.xprocspec: Notes fallback mechanism](https://github.com/nlbdev/pipeline/blob/999e94f5280c83739801a7a38ea0f8232a2ceaed/modules/nlb/book-to-pef/src/test/xprocspec/test_html-to-pef_notes.xprocspec#L591)
- [x] [test_html-to-pef_notes.xprocspec: Volume notes](https://github.com/nlbdev/pipeline/blob/999e94f5280c83739801a7a38ea0f8232a2ceaed/modules/nlb/book-to-pef/src/test/xprocspec/test_html-to-pef_notes.xprocspec#L109)

**Comment by bertfrees** [comment]
I fixed all the tests. I'll push tomorrow.

**Comment by KariRudjord** [comment]
I'm not quite sure what to test her. Can you help me?

**Comment by bertfrees** [comment]
If you have tested the issues where Jostein wrote "Replaced by #23", you have done the most important part I think. I'm not sure what else you could test. In theory everything that worked for DTBook now also works with HTML, so you may test anything you want.

**Comment by josteinaj** [comment]
@KariRudjord I don't think you need to test anything here. These are just automated tests.
