### ISSUE TITLE
Review test data from snaekobbi project

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#25]
https://github.com/snaekobbi/testing/tree/master/Test%20data

We could probably reuse data from there for automatic or manual testing.

**Comment by josteinaj** [comment]
@KariRudjord @usama49 maybe one of you could check the snaekobbi repository linked to above and see if the test data there is something we can reuse for testing now?

**Comment by KariRudjord** [comment]
Much of this is doublechecked already. We could retest notes (sprint 8), TOC and table-to-list (sprint 7) and hard page breaks and orphan/widow control (sprint 4).

**Comment by josteinaj** [comment]
Ok. I created issues for retesting: #26 #27 #28 #29 (no testing to be done until a new version is installed of course).

The test data in the snaekobbi repository is input DTBook and expected output PEF, right? So I could set up some automated tests for them?

**Comment by KariRudjord** [comment]
Yes, that is what I sent each time. Expected output may be absent if NorBraille doesn't have the solution, e.g. the solution for notes is another than the one we have in NorBraille. And NorBraille doesn't hand tables.

**Comment by josteinaj** [comment]
Ok, thanks. I've created issue #30 for me to create automated tests. Closing this issue.
