### ISSUE TITLE
Retest TOC (from sprint 7)

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#27]

**Comment by matskober** [comment]
Toc listings has to much line space
[results (4).zip](https://github.com/nlbdev/pipeline/files/1127786/results.4.zip)

**Comment by josteinaj** [comment]
Ok. Otherwise it looks ok?

**Comment by matskober** [comment]
Yes it looks ok. (If anything, the left margin cold be smaller.)

**Comment by josteinaj** [comment]
Ok good. We have an issue for the margins here: #52 so I'm closing this on.
