### ISSUE TITLE
Retest hard page breaks and orphan/widow control (sprint 4)

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#29]

**Comment by matskober** [comment]
Orphan/widow control seems to work as intended!
![image](https://user-images.githubusercontent.com/8014898/33370842-ac2ffee4-d4f0-11e7-9602-fe2801bce518.png)

**Comment by matskober** [comment]
The 'hard page breaks' referred to in  #29 - is that connected to the orphan/widow issue, or is it 'page-breake-before'-matter?

**Comment by josteinaj** [comment]
Not sure. `page-break-before` should already work, so I suppose the issue to test is "orphan/widow control", but I don't know what kind of "control" this refers to. @KariRudjord do you remember?

**Comment by KariRudjord** [comment]
It seems from Mats' example above that orphan/widow is working like intended, so i close the issue.
