### ISSUE TITLE
Start using the braille script(s) in production

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#31]
- [x] Set up automatic conversions of all incoming EPUBs (#41)
- [ ] Write production routines for manual production using the Web UI
- [x] Consider setting up a separate server for production rather than using the same server as for testing

**Comment by josteinaj** [comment]
@KariRudjord do you think we can already write a production routine description or should we wait? Also, who should do it?

**Comment by josteinaj** [comment]
@KariRudjord I moved this to "ready for testing" so you can decide what to do with this issue.

**Comment by KariRudjord** [comment]
Works.
