### ISSUE TITLE
move colophon, hide titlepage and print toc

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#32]
Maybe delete most of it and keep only dedications and forewords?

**Comment by KariRudjord** [comment]
Dedications, quotes and forewords, yes. And we have to be sure that translator is present. It is supposed to be included in metadata, but doesn't always appear there. If we find a solution, Olav is interested to participate in the discussion.

**Comment by matskober** [comment]
Dedications, etc in colophon, might be considered a markup issue; I suspect it is a print book phenomenon - I have yet not seen this in publisher EPUBs.  
I suggest: 
1. Info on Publisher (of the version we transliterate) and year to front page (from metadata)
2. Translator info should go on front page, as should original title (from metadata)
3. The colophon form the print book is moved to the end of the publication. (As it is in most commercial EPUBs)

**Comment by josteinaj** [comment]
Closely related (duplicate?): #55
Closely related: #51

**Comment by KariRudjord** [comment]
We had a discussion on colophon issues some time ago. Can we make something like this?

- class=colophon - move to end of book. But original title to Om boka if possible.
- class=titlepage - hide, but publisher and year to Om boka if possible. (If not possible, this will be present in the colophon in end of book).
- class=toc (that is print toc) - hide
- class=dedication and class preface stays in front of vol.1 after TOC
- is there a class=quotes?? Sometimes you have a poem or a quote from another novel in a novel. How will that be marked? Should stay in front of book like dedication.

**Comment by josteinaj** [comment]
- colophon/titlepage/toc/dedication: ok, we can do that
- quotes: there's no such class that I'm aware of but everything in frontmatter except colophon, titlepage and toc will remain there as-is anyway, so we probably don't have to treat in any special way?

**Comment by KariRudjord** [comment]
Yes, I see it is marked up as a blockquote in one book. Maybe that is the standard.

**Comment by josteinaj** [comment]
Now moving colophon to the end of backmatter, and removing existing titlepage and toc. Test server will be updated soon.

**Comment by KariRudjord** [comment]
Colophon is still in front of the book, but maybe you have not updated the server yet?

**Comment by josteinaj** [comment]
I had to fix some minor issues before installing, but it should be installed now so you can try again.

**Comment by KariRudjord** [comment]
Yes, now it's placed in back of book, great! Could you add empty side before colophone so it is divided from the rest of the text and start on right hand page?

Some book have a list in frontmatter that shows all the books from the author. In talking books they leave out this list, and if possible I want the same habit in braille books. Is that possible in any way. Onlyd marked as a regular level1 in the example i have found. Maybe something for our oppmerking i EPUB meeting soon.

I'll try to find more testexamples with different content in frontmatter.
[558905.Theoldmanandthesea.7z.zip](https://github.com/nlbdev/pipeline/files/1517117/558905.Theoldmanandthesea.7z.zip)

**Comment by josteinaj** [comment]
Looking at your job (1761) it seems that the colophon starts on the right hand page. It's a level1 and shouldn't need to be treated any differently than other level1s I think? If you want an empty page on the previous page and also have it start on the right hand page, then you'll get two blank pages before the colophon, but maybe that's fine?

Removing book lists: yes we need to have it marked up with a class and/or epub:type so that we can filter it out automatically.

**Comment by KariRudjord** [comment]
Maybe its easier to divide it from the main text with a headline? &lt;h1&gt;Bokinformasjon inserted before colophone text. Bokinformasjon is the word used in talking books, so I think we can use that.

**Comment by KariRudjord** [comment]
Sorry - now I'm shouting again :-) I'm not angry :-)

**Comment by josteinaj** [comment]
If we insert a headline `<h1>Bokinformasjon</h1>` then that's probably something we want to do directly in our books and not as part of this script?

**Comment by KariRudjord** [comment]
Like headlines Om boka, Innhold and Fotnoter?

**Comment by josteinaj** [comment]
No I meant we should probably do it in our master EPUBs. But yes, maybe as you say we could add a `<h1>Bokinformasjon</h1>` headline for colophons with no pre-existing headline?

**Comment by KariRudjord** [comment]
Job 1843 have examples on content in frontmatter, @josteinaj (prodnote, dedications etc) And yes, they are all level1 like we talked about.

**Comment by josteinaj** [comment]
So, the first two frontmatter issues we talked about:
- [x] hide the jacketcopy/cover ~~hide prodnotes in jacketcopy~~
- [x] toc should start at 3rd cell (not 4th as it is now)

And the third issue we talked about: empty rows between persons on the dedication page. In your job, this is the input:
```xml
<level1 id="level1_5" class="dedication">
    <pagenum id="page-5" page="normal">5</pagenum>
    <p><em>to Charlie Scribner and to Max Perkins</em></p>
    <pagenum id="page-6" page="normal">6</pagenum>
</level1>
```
And the output is:
```
=   2TO ,CHARLIE ,SCRIBNER AND  
= TO ,MAX ,PERKINS;             
```

Since both names are in the same paragraph, I don't think it's practically possible to insert a line here (as it isn't double linespacing we're after). If I change the input to this however:
```xml
<level1 id="level1_5" class="dedication">
    <pagenum id="page-5" page="normal">5</pagenum>
    <p><em>to Charlie Scribner</em></p>
    <p><em>and to Max Perkins</em></p>
    <pagenum id="page-6" page="normal">6</pagenum>
</level1>
```
Then this is the output:
```
=   2TO ,CHARLIE ,SCRIBNER;     
=   2AND TO ,MAX ,PERKINS;      
```

Here we could add a 1 row bottom margin to all paragraphs on the dedication page and get this:
```
=   2TO ,CHARLIE ,SCRIBNER;     
                                
=   2AND TO ,MAX ,PERKINS;      
```
Would that be ok?

**Comment by KariRudjord** [comment]
Just forget the last issue. The two first I want changed, yes.

**Comment by josteinaj** [comment]
@KariRudjord according to @matskober we should remove or hide any existing jacketcopy/cover? (see https://github.com/nlbdev/pipeline/issues/122#issuecomment-348967914)

Or do we still need the pre-existing cover to be included in frontmatter after the toc ?

**Comment by KariRudjord** [comment]
We should hide the jacketcopy!

**Comment by josteinaj** [comment]
Ok, great :)
