### ISSUE TITLE
Acrynyms with genitive "s" / Akronymer med genitivs-s

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#35]
(norwegian)

*from Trello-board (@matskober):*

Legge inn akronymer med genitivs-s (f.eks. NLBs. I punktskrift skal det være et tegn som markerer skillet mellom akronymet og genitivs-s - 56). Liste over akronymer er skaffet fra Mari

**Comment by josteinaj** [comment]
*from Trello-board (@matskober):*

Det lyder rart at det ikke skal gå å lage en regel som sier at forekomster av små bokstaver i en gruppe av store bokstaver skal markeres med småbokstavtegn. (Det er jo på en måte bare å speilvende regelen som i dag markerer forekomsten av store bokstaver?) Men det er kanskje ikke det du sier?

Svenskene og UEB bruker generelt "lukketegn" for å markere denne endringen, det burde kanskje OUB vurdere å innføre her også; så kan man markere hele avsnitt med storbokstavtegn ...

Hvis vi tagger 'NLBs' slik: `<acronym>NLB</acronym>`s , så burde det jo være mulig med en regel som som sier at forekomster av små bokstaver som følger umiddelbart etter en acronym skal ha en markering. (Mens den ikke er nødvendig her: NLB-ansatt? )

**Comment by josteinaj** [comment]
*from Trello-board (@KariRudjord):*

Vi har dessverre ikke funnet noen annen måte å gjøre dette på enn manuelt. Planen er å gå gjennom lista slik at den automatisk lager skillet der det forekommer. Listen trenger ikke nødvendigvis bare inneholde akronymer, men også andre ord der det er skille mellom stor og liten bokstav. Kjemiske formler må vi også finne en løsning på, med nedre eller øvre indeks som f.eks. H2O (for anledning skrevet ukorrekt :-) )

**Comment by josteinaj** [comment]
*from Trello-board (@matskober):*

Punktskifttegnet som det snakkes om her, er et såkalt "småbokstavtegn". I utgangspunktet bør kanskje dette ikke knyttes for tett opp til akronymer; skifte fra grupper av store til forekomster av små bokstaver kan forekomme i andre kontekster, som layoutmessig effekt i barne/ungdoms bøker, f.eks.

Likevel bør kanskje akronymer være tagget opp i EPUB-en? I dag gjør jeg det ved hjelp av søk/erstatt i DTBook - særlig i sjangerlitteraturen er det mye FBI, CIA, SMS, osv - for å få det riktig I NorBraille. Maris liste kunne kanskje gjøre nytte for seg i en preprossesering eller vidreforedling av grunnlagsfil?

**Comment by matskober** [comment]
This works as it should!

![image](https://user-images.githubusercontent.com/8014898/33373583-81736df8-d4fa-11e7-8ade-2b26e4f160fc.png)
