### ISSUE TITLE
Web UI: adjusting page width/length not working

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#36]
*from Trello-board:*

Fix it if it's simple. If not, we remove the option and do it in CSS. It's something we rarely have to adjust.

**Comment by josteinaj** [comment]
This seems to work for me.

@KariRudjord / @matskober is this still an issue?

**Comment by KariRudjord** [comment]
It does not work when I adjust it in GUI, but it is not important, so it's fine with me to archive it. Agree, @matskober ?

**Comment by bertfrees** [comment]
In that case we should probably hide the option.

**Comment by matskober** [comment]
To be able to adjust the length of the lines is a nice feature, and it
works!

**Comment by KariRudjord** [comment]
Then it must be me :-) Every time I try, I get Failed. But then I close this!
