### ISSUE TITLE
Allow uploading and using more than one CSS at a time

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#37]
*from Trello-board*

**Comment by josteinaj** [comment]
@usama49 @KariRudjord @matskober I think this works now, right?

**Comment by matskober** [comment]
@josteinaj @usama49 @bertfrees  @KariRudjord 

Yes it works to add css. But only one css; but that's maybe how it's supposed to be?

**Comment by josteinaj** [comment]
We could allow more than one CSS, I'll rename the issue.

**Comment by bertfrees** [comment]
What exactly is the issue?

**Comment by KariRudjord** [comment]
I don't know. I would think all can be added in one additional CSS?

**Comment by josteinaj** [comment]
The script accepts one CSS file to be selected, but @matskober would like to be able to select multiple CSS files. So not a bug (which I thought at first) but a feature request.

It should already be possible to attach multiple CSS files by `<?xml-model ...>`, `<style>` or `<link>` though (I think). Just not as a script argument (i.e. the Web UI widget).

**Comment by bertfrees** [comment]
OK I see, in the NLB script you made the option into a `anyFileURI`. In the generic script it is just a `string` so you can specify multiple stylesheets by simply separating them with spaces. All you need is a `px:sequence="true"`, right?

**Comment by josteinaj** [comment]
Yes, probably.

Jostein

3. jul. 2017 12:36 p.m. skrev "Bert Frees" <notifications@github.com>:

**Comment by matskober** [comment]
Don't know if this is relevant; I raised the question initially because I assumed it would be possible - but I don't know if it is something that is needed.

**Comment by josteinaj** [comment]
Ok. It should work now though, have you tested it?

**Comment by bertfrees** [comment]
For this to work the comma that is used to separate the style sheets should become a space.
