### ISSUE TITLE
Use the liblouis UEB table for english

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#40]
*from Trello-board*

**Comment by josteinaj** [comment]
@KariRudjord english braille works now, right? It respects the `xml:lang="en"`? So we can close this one?

**Comment by matskober** [comment]
When "alltid norsk"-box is not checked, the production fails: pf:text-transform failed (job#1050 EPUB3 to pef) and #1053, DTBook to pef).

**Comment by KariRudjord** [comment]
Working

**Comment by matskober** [comment]
I still get "8-dot: Yes", when unchecking "alltid norsk" and the xml:lang="en". But that's a different issue, maybe?
