### ISSUE TITLE
Proposal for automatic lending (braille) / Forslag til automatisert utlån (punktskrift)

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#42]
(norwegian)

*from Trello:*

Forslag til automatisert utlån: legge PEF på område der trykkeriet kan hente filene selv. Generere e-post med lånerinformasjon automatisk til trykkeri. Ammar. Kari tar en prat med utlån/formidling om ev feilbestillinger.

**Comment by josteinaj** [comment]
This is being worked on by @usama49 and @KariRudjord. Out of scope for the braille scripts themselves.

**Comment by KariRudjord** [comment]
Done
