### ISSUE TITLE
braille: add CSS for making tables into lists

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#45]
*from Trello-board:*

(CSS is under AT). What to do if a table cannot be rendered as a list?

**Comment by KariRudjord** [comment]
If a table cannot be rendered as a list, it will not be reproduced. Add the text: "Tabell utelatt."

**Comment by josteinaj** [comment]
Links to table CSS from other snaekobbi participants:

- [Generic tables](https://github.com/daisy/pipeline-mod-braille/blob/develop/pipeline-braille-scripts/dtbook-to-pef/src/main/resources/css/default.css#L54)
- [SBS tables](https://github.com/sbsdev/pipeline/blob/sbs/modules/sbs/braille/src/main/resources/css/default.scss#L1012)
- [Celia tables](https://github.com/celiafi/pipeline-mod-celia/blob/master/src/main/resources/css/celia-default.scss#L238)
- [Dedicon tables](https://github.com/snaekobbi/pipeline-mod-dedicon/blob/master/src/main/resources/css/dedicon-default.scss#L377)
- [Nota tables](https://github.com/snaekobbi/pipeline-mod-nota/blob/master/src/main/resources/css/default.scss#L316)

**Comment by bertfrees** [comment]
I'm gonna need some requirements and tests before I can implement this.

**Comment by josteinaj** [comment]
Ok. Since we don't have this today, we don't have an expected output ready. Would it be possible for you to provide an initial suggestion, and then @KariRudjord can say if it looks fine or needs adjustments?

**Comment by bertfrees** [comment]
Ok.

**Comment by bertfrees** [comment]
I have made an initial suggestion. Can be tested now.

**Comment by josteinaj** [comment]
@KariRudjord You need to add the `table-as-list` class to the table that you want to become a list.

For instance, this:

```html
<table class="table-as-list">
    <caption>caption</caption>
    <tr>
        <th/>
        <th>A</th>
        <th>B</th>
    </tr>
    <tbody>
        <tr>
            <th>I</th>
            <td>a</td>
            <td>b</td>
        </tr>
        <tr>
            <th>II</th>
            <td>c</td>
            <td>d</td>
        </tr>
    </tbody>
</table>
```

will become this (replaced with characters for readability):

```xml
<row/>
<row>⠀⠀⠀⠀caption</row>
<row/>
<row>⠀⠀⠀⠀´tabell⠀starter</row>
<row/>
<row>⠀⠀´i:⠀´a:⠀a</row>
<row>⠀⠀⠀⠀´b:⠀b</row>
<row>⠀⠀´´ii:⠀´a:⠀c</row>
<row>⠀⠀⠀⠀´b:⠀d</row>
<row/>
<row>⠀⠀⠀⠀´tabell⠀slutter</row>
<row/>
```

You should try with some different existing tables and see how it looks.

**Comment by KariRudjord** [comment]
I've made some test examples: (for some reason the zipped xml will not be added here, I can email it if you want). 

By now it seems like everything is set as columns, not lists. I don't know if it is the markup or the CSS.
[Tables.Examples-originalandPIP.docx](https://github.com/nlbdev/pipeline/files/1413692/Tables.Examples-originalandPIP.docx)

**Comment by josteinaj** [comment]
After discussing a bit with Kari on slack, I'm gonna create some input/output XML based on Karis examples. @KariRudjord will have to approve the examples, so that we get the desired layout.

The first examples shows the alphabet and is a 6x5 table (6 columns). Considering that we need space for a border and table cell margins and the available row width is 30 braille cells, we can't fit any more that 3 columns of this table without breaking table cells into multiple lines. So this very simple example should tell us that tables with more than 3 columns should probably not be rendered as tables in braille. I've made an equivalent 3x10 table for testing:

```xml
<table>
    <tbody>
        <tr><td>A a</td><td>B b</td><td>C c</td></tr>
        <tr><td>D d</td><td>E e</td><td>F f</td></tr>
        <tr><td>G g</td><td>H h</td><td>I i</td></tr>
        <tr><td>J j</td><td>K k</td><td>L l</td></tr>
        <tr><td>M m</td><td>N n</td><td>O o</td></tr>
        <tr><td>P p</td><td>Q q</td><td>R r</td></tr>
        <tr><td>S s</td><td>T t</td><td>U u</td></tr>
        <tr><td>V v</td><td>W w</td><td>X x</td></tr>
        <tr><td>Y y</td><td>Z z</td><td>Æ æ</td></tr>
        <tr><td>Ø ø</td><td>Å å</td><td/></tr>
    </tbody>
</table>
```

```xml
<page>
    <row>⠀⠀⠋⠉⠉⠉⠉⠿⠉⠉⠉⠉⠉⠉⠿⠉⠉⠉⠉⠙</row>
    <row>⠀⠀⠠⠁⠀⠁⠀⠿⠀⠠⠃⠀⠃⠀⠿⠀⠠⠉⠀⠉</row>
    <row>⠀⠀⠠⠙⠀⠙⠀⠿⠀⠠⠑⠀⠑⠀⠿⠀⠠⠋⠀⠋</row>
    <row>⠀⠀⠠⠛⠀⠛⠀⠿⠀⠠⠓⠀⠓⠀⠿⠀⠠⠊⠀⠊</row>
    <row>⠀⠀⠠⠚⠀⠚⠀⠿⠀⠠⠅⠀⠅⠀⠿⠀⠠⠇⠀⠇</row>
    <row>⠀⠀⠠⠍⠀⠍⠀⠿⠀⠠⠝⠀⠝⠀⠿⠀⠠⠕⠀⠕</row>
    <row>⠀⠀⠠⠏⠀⠏⠀⠿⠀⠠⠟⠀⠟⠀⠿⠀⠠⠗⠀⠗</row>
    <row>⠀⠀⠠⠎⠀⠎⠀⠿⠀⠠⠞⠀⠞⠀⠿⠀⠠⠥⠀⠥</row>
    <row>⠀⠀⠠⠧⠀⠧⠀⠿⠀⠠⠺⠀⠺⠀⠿⠀⠠⠭⠀⠭</row>
    <row>⠀⠀⠠⠽⠀⠽⠀⠿⠀⠠⠵⠀⠵⠀⠿⠀⠠⠜⠀⠜</row>
    <row>⠀⠀⠠⠪⠀⠪⠀⠿⠀⠠⠡⠀⠡⠀⠿⠀⠀⠀⠀⠀</row>
    <row>⠀⠀⠦⠤⠤⠤⠤⠿⠤⠤⠤⠤⠤⠤⠿⠤⠤⠤⠤⠴</row>
</page>
```

**Comment by josteinaj** [comment]
Actually, this issue is about making tables into lists. So @KariRudjord: if you test the `table-as-list`, and it works, then you can move it to Done. I'm going to add the examples to #8 instead.

**Comment by KariRudjord** [comment]
It works, but two problems:
1. When text in a cell is more than 1 line, it need to extra indents. Otherwise it will be interpreted as a new cell. 
2. when a cell is empty, the information that it is actually empty disappear, eg. here on Havgregryn:
```
,TABELL STARTER             
                                
  ,,MATVARE                     
    ,,GI                        
    ,,GB                        
    ,,PORSJONSST[RRELSE         
    8,,GRAM0                    
  ,HAVREGRYN                    
    #AJ                         
    #EJ                         
  ,FROKOSTBLANDING              
    #DC                         
    #G                          
    #CJ              
```

I don't quite know how it should be marked (I've emailed someone with experience in this but waiting for answer).  I assume we can implement a rule and suggest that we put "tom" for now and change it later if it should be marked otherwise.

**Comment by KariRudjord** [comment]
here is the xml

```xml
<level1>
   <table class="table-as-list">
      <tr>
          <td>MATVARE</td>
          <td>GI</td>
          <td>GB</td>
          <td>PORSJONSSTØRRELSE (GRAM)</td>
      </tr>
      <tr>
          <td>Havregryn</td>
          <td> </td>
          <td>10</td>
          <td>50</td>
      </tr>
      <tr>
          <td>Frokostblanding</td>
          <td>43</td>
          <td>7</td>
          <td>30</td>
      </tr>
   </table>
```

**Comment by bertfrees** [comment]
OK. Note that this was just a random initial proposal I made, just to give you an idea of what is possible. You can modify it completely.

**Comment by KariRudjord** [comment]
Good! We might have different rules for different tables, after what kind of content it has, but I hope we can come down with a set of rules to choose between. Probably we can benefit from this work also in our text to speech production - we have about the same challenges.

**Comment by josteinaj** [comment]
I think this is ready for testing?

**Comment by bertfrees** [comment]
Yes
