### ISSUE TITLE
braille: add 'Bildebeskrivelse:' before images with alt-text

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#47]
*from Trello-board:*

Alternative text for images (`<img src="" alt="">`). Can you add in CSS so that when the `alt` attribute has content, then the following text comes in front: "Bildebeskrivelse:". As with "Bildetekst:" there should be a blank line above and below and two indents from the margin on the whole text.

**Comment by josteinaj** [comment]
@KariRudjord this can be tested now

**Comment by matskober** [comment]
[results (15).zip](https://github.com/nlbdev/pipeline/files/1251823/results.15.zip)
Job #746
Tested "billedbeskrivelse" before img's alt="" - it is working. 
@KariRudjord @josteinaj @usama49
