### ISSUE TITLE
braille: NLB-CSS: page: margin-right=0 size: 32 28

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#48]
*from Trello-board*

**Comment by josteinaj** [comment]
@KariRudjord @matskober should page size be 32 rows x 28 columns? Now it's 30x28 I think.

**Comment by KariRudjord** [comment]
It must include margins and header/footer. 28 rows and 30 cells is for the text @josteinaj

**Comment by josteinaj** [comment]
Ok. In the PEFs we produce with NorBraille I see volumes are declared like this, so I suppose we should increase the default number of columns from 30 to 32:

```xml
<volume cols="32" rows="28" rowgap="0" duplex="true">
```

**Comment by josteinaj** [comment]
The page dimensions have been updated now. Also the margins. Ready to test.

**Comment by matskober** [comment]
This works.
