### ISSUE TITLE
braille CSS: translator / oversetter

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#50]
(norwegian)

*from Trello-board*

NLB-CSS: title page: -          «Oversatt av» skal kun stå når det er oversetter. (Nå kommer det med også på bøker som ikke er oversatt)

**Comment by josteinaj** [comment]
Fixed in 84739a2217bcc9cbd441294e2f5f56e3a6c28f6e.

**Comment by KariRudjord** [comment]
Translator doesn't appear on title page although it is present in metadata:
```xml
<meta name="dc:Contributor" content="Translator, Tex the"/>
```

**Comment by josteinaj** [comment]
Try adding the `role` attribute to the meta element:

```xml
<meta name="dc:Contributor" role="translator" content="Translator, Tex the"/>
```

**Comment by KariRudjord** [comment]
Book is not valid then:
Description: Attribute "role" must be declared for element type "meta".

**Comment by KariRudjord** [comment]
But guess what, it worked anyway! Is this something we will get into our metadata on regular basis?

**Comment by josteinaj** [comment]
Oh, it seems the `role` attribute is for the OPF in a DAISY 3 publication, so that's not valid in a DTBook, no. I misread the [DAISY 3 specification](http://www.niso.org/workrooms/daisy/Z39-86-2005.html). It won't work in a HTML document either, so we need some way of representing the translator in the metadata anyway.

Maybe we should just say:
```xml
<meta name="translator" content="Translator, Tex the"/>
```

I'll have to search around a bit to find out if there's a "correct" way to do it. Until then you'll have to use the invalid `role="translator"` for testing.

Anyway, this issue works now I think? The layout? I created a separate issue for the translator metadata markup here: #131

**Comment by josteinaj** [comment]
Let's use `dc:contributor.translator` for translator. See: #131
