### ISSUE TITLE
braille CSS: "NLB", "Norge 2016", placement / plassering

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#51]
(norwegian)

*from Trello-board*

NLB-CSS: title-page: De to linjene «NLB» og «Norge 2016» - skal stå uten blank linje mellom (hvis det er vanskelig, kan de stå på samme linje: «NLB, Norge 2016»)

**Comment by josteinaj** [comment]
Fixed in 84739a2217bcc9cbd441294e2f5f56e3a6c28f6e.

**Comment by KariRudjord** [comment]
Working
