### ISSUE TITLE
braille CSS: toc margins and headline / innholdsfortegnelse-marger og tittel

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#52]
(norwegian)

*from Trello-board*

NLB-CSS: TOC: endre følgende i NLB default CSS: margin-left: 0 (begge steder) og margin-top: 0 (begge steder).   Fast overskrift (h1) over innholdsfortegnelsen med teksten: Innhold

**Comment by KariRudjord** [comment]
Det vil si at det ikke blir mellomrom mellom linjene i TOC'en, @josteinaj ? Slik det er nå, tar TOC'en mye plass pga mellomrommene.

**Comment by josteinaj** [comment]
Ok. Ja det kan vi fikse.

**Comment by josteinaj** [comment]
<img width="796" alt="compare_print_toc" src="https://user-images.githubusercontent.com/295481/27964552-f849ca96-6338-11e7-99ff-587db5ac16cd.PNG">

From Slack, @matskober compares EPUB (left) with DTBook (right). The smaller margins used with EPUB is preferable.

**Comment by josteinaj** [comment]
I think this is fixed in 02ab17fccbaa7533c675445fa57eb149307a3180, but should be tested.

**Comment by KariRudjord** [comment]
It's still two rows between the entries. Takes a lot of space. Should be row by row without space

![image](https://user-images.githubusercontent.com/12409918/31940564-e59c93d4-b8be-11e7-8f13-4124e5eeca03.png)

**Comment by matskober** [comment]
Job #1504;

It seems that the margin-top gets right in the volume specific tocs, but not in the toc in the first volume

**Comment by matskober** [comment]
This worked:
#generated-volume-toc li {
       
        margin-top: 0;
      
}

#generated-volume-toc li a::after {

        margin-top: 0;
       
}
#generated-document-toc li {
            margin-top: 0;

}
generated-document-toc li a::after {
            margin-top: 0;

}

**Comment by KariRudjord** [comment]
Working.
