### ISSUE TITLE
Use other languages straight from liblouis

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#54]
- ~~New table for sami languages.~~ Moved here: #101
- ~~New table for Old West Norse ("norrønt") or Old Norwegian ("gammelnorsk").~~ Moved here: #98
- ~~Use the liblouis UEB table for english.~~ Issue is here: #40
- Use other languages straight from liblouis.

- [ ] Translator should switch language depending on `xml:lang` and `lang` attributes.
- [ ] Should probably also have an option to force usage of the standard norwegian table regardless of the language in the content. (option and pending test added in 7e7a416e53be8a994dcd7b8dbb92a8cbe4d6a16a)

**Comment by josteinaj** [comment]
@bertfrees FYI: This issue is something we can look at if there's time at the end of the sprint. Nothing to worry about just yet, but just in case there's time.

**Comment by josteinaj** [comment]
see also #40

**Comment by KariRudjord** [comment]
Testet with danish, swedish, german, greek and english.
The test will only pass through with norwegian and english, but it will not open either in preview or PEF.

Could not find result: http://localhost:8181/ws/jobs/9670f689-3b4e-4d9a-bca8-baa6c80852de/result/option/preview-output-dir/idx/preview-output-dir/spr%C3%A5ktest.pef.html

**Comment by josteinaj** [comment]
The resulting file has the name `spr├еktest.pef.html` instead of `språktest.html`, so something is wrong with the character encoding.

Created issue: daisy/pipeline-webui#112

**Comment by KariRudjord** [comment]
I was not aware of the å problem, it passed with an a in file name. It seems to be norwegian braille code even when using <p xml:lang="en">

**Comment by bertfrees** [comment]
> Translator should switch language depending on `xml:lang` and `lang` attributes

What do you think about also using the `dc:language` metadata field? Which of these three is strongest?

**Comment by josteinaj** [comment]
I would say `xml:lang > lang > dc:language` (prefer left).

It would probably be a warning or error in a validation tool though. It's not something that should occur.

**Comment by bertfrees** [comment]
```scss
*[xml|lang]:not([xml|lang|="no"]), *[lang]:not([lang|="no"]) {
        text-transform: uncontracted;
}
```

Is this CSS rule still desired?

**Comment by bertfrees** [comment]
Which other languages should be supported but do not work at the moment?

**Comment by josteinaj** [comment]
Ideally everything that is available in liblouis by default would be great. I know @KariRudjord tested 3 weeks ago and got the error `Could not find a sub-translator for language de (uncontracted)`, so at least we had trouble with german. Do you need a list of languages?

**Comment by bertfrees** [comment]
OK yeah, the problem is that at the moment, for languages that have contractions, the uncontracted variants are not discoverable. I'll work on that. I don't really need a list of languages now that I know what the problem is, but it could be useful to know anyway, for creating tests.

**Comment by bertfrees** [comment]
> Should probably also have an option to force usage of the standard norwegian table regardless of the language in the content. (option and pending test added in 7e7a416)

@josteinaj It seems like this already works? You enabled the test in 52930b2.

**Comment by bertfrees** [comment]
>  Use other languages straight from liblouis.

This should now have been fixed.

> Translator should switch language depending on `xml:lang` and `lang` attributes.

This hasn't been done yet.

In addition, Norwegian within a passage in another language works now.

**Comment by bertfrees** [comment]
@josteinaj I also fixed a wrong test here: 08e569b. Did you maybe create that test in response to issue https://github.com/nlbdev/pipeline/issues/40? Does this mean it is no longer an issue?

**Comment by josteinaj** [comment]
> Did you maybe create that test in response to issue #40? Does this mean it is no longer an issue?

Yes probably.

**Comment by matskober** [comment]
[job1404.zip](https://github.com/nlbdev/pipeline/files/1450156/job1404.zip)
Job1404 had the "always Norwegian" option unchecked - the production failed

[job1403.zip](https://github.com/nlbdev/pipeline/files/1450164/job1403.zip)
Job1403 had the "always Norwegian" checked - the hebrew letters turn all to dots 26

**Comment by bertfrees** [comment]
> the hebrew letters turn all to dots 26

Not sure if we can do something about that. Does the Norwegian braille code have any rules for Hebrew letters?

**Comment by matskober** [comment]
There is a section in the Norwegian liblouis file that says "Hebrew" ?

**Comment by josteinaj** [comment]
@matskober it is defined in the 8-dot table here: https://github.com/liblouis/liblouis/blob/275b28883c49aa691306430549a17be781fe360e/tables/no-no-8dot.utb#L334

It does not seem to be defined for 6-dot. If there is a norwegian standard for hebrew in 6-dot we could add it to the table.

**Comment by josteinaj** [comment]
All undefined characters are represented as dot 26:

https://github.com/liblouis/liblouis/blob/ddd8053abd3f1153af0daf788f24b1a07385e80e/tables/no-no-chardefs6.uti#L191

**Comment by matskober** [comment]
Hebrew braille is based on English braille, so it is just different when it
comes to the alphabet, as far as I have been able to grasp. (And of course
that print Hebrew is read from right to left, while braille Hebrew is read
from left to right.)

**Comment by bertfrees** [comment]
> print Hebrew is read from right to left, while braille Hebrew is read from left to right

Really? That's peculiar. Lucky for us developers of braille translators/formatters, but strange for braille readers.

**Comment by matskober** [comment]
It's the same with Arabic and other "right-to-left"-languages, as far as I
know; in Braille they are "mirrored" into the left-to-right regime. I
believe it is a historical production tool limitation behind this; I can't
see any reason why it should preferable to read braille from right to
left.

**Comment by matskober** [comment]
I can't see any reason why it should preferable to read braille from *left
to right*.

**Comment by bertfrees** [comment]
OK makes sense.
