### ISSUE TITLE
braille: Colophon info on first page / Ang layout / hefteinndeling / forsideinfo / kolofon mm

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#55]
(norwegian)

*from Trello (@matskober):*

**Comment by josteinaj** [comment]
*from Trello (@matskober):*

Første venstreside i det første heftet: Relevante opplysninger fra kolofon
(vil variere), pluss transkripsjonsinnstillinger/opplysninger ("Om boka", i dag - burde kanskje stå "om punktskriftutgaven" eller noe lignende)

**Comment by josteinaj** [comment]
*from Trello (@matskober):*

Forsiden kunne benyttes bedre enn vi gjør i dag; forslår at vi drar en del av kolofoninfoen og metadata dit.
Øverst på forsiden, venstrestilt: Forfatter (max tre linjer)
tittel (max tre linjer)
eventuell oversetter (max tre linjer)
Forlag, sted, år (max tre linjer)

Nederst på forsiden
NLB, år
total sidetall og antall hefter i tittel
hefte x av y, (pluss pagespan i heftet)

**Comment by josteinaj** [comment]
@matskober @KariRudjord is this an important issue or can we postpone this until later?

**Comment by KariRudjord** [comment]
We've just talked about it, @josteinaj. We would like to get it fixed. If it is something that involve Bert, we should do it now. If not, it can wait.

**Comment by josteinaj** [comment]
I believe this is something we don't need help to do ourselves.

**Comment by josteinaj** [comment]
Fixed in 84739a2217bcc9cbd441294e2f5f56e3a6c28f6e and 02ab17fccbaa7533c675445fa57eb149307a3180.
