### ISSUE TITLE
Switch position of generated "Om boka" and TOC

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#57]
*from Trello:*

TOC first, then "Om boka".

@matskober correct?

**Comment by josteinaj** [comment]
@matskober @KariRudjord what do you think?

**Comment by matskober** [comment]
No strong opinion on the subject, but to me it seems natural to keep the
"Om *punktskrift*boka" separate form the book's content. If the toc we are
talking about replaces the print book toc, the generated  toc will seem
more integrated in the book than the "Om *punktskrift*boka". Therefor I
suggest that we put the "Om *punktskrift*boka" at the back of the front
page of the first volume, and the toc starting on page 3. (The first volume
toc is different for the following volume tocs anyhow.)
Also, a different but related matter: no colophon in the first volume #55

**Comment by KariRudjord** [comment]
Etter en liten samtale har Mats og jeg kommet fram til rekkefølgen Tittelside, Om boka, TOC. Tror ikke noe er endret her, hvis dere ikke har gjort noe denne uka, @josteinaj Skal jeg teste og sjekke?

**Comment by josteinaj** [comment]
> The first volume toc is different for the following volume tocs

Currently I think the TOC is only for the chapters in the volume containing that TOC. Should the first TOC be a TOC for the entire document, across all volumes?

**Comment by matskober** [comment]
In my opinion, yeah; First volume toc showing the full book (and starting
on page 3). All other volumes: toc starting on page 2  - only referring to
chapters the volume is containing.

Mats

**Comment by KariRudjord** [comment]
Yes, first volume have full TOC and the other volumes volume-spesific TOC. It has been working before, should I test it again?

**Comment by josteinaj** [comment]
Ok. I'll create some automated tests for it first. I don't think it currently works that way so I'll have to change it.

**Comment by matskober** [comment]
Believe it's all volume specific tocs in all volumes at the moment

**Comment by josteinaj** [comment]
This can now be tested.

Volume 1 should start with: titlepage + about page + document toc
Volume 2 and up should start with: titlepage + volume toc

**Comment by KariRudjord** [comment]
Working.
