### ISSUE TITLE
All elements before the first chapter gets their own <section>

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#58]
*from Trello:*

Is this intentional?

**Comment by bertfrees** [comment]
You mean that the TOC starts in a new section? This is because of https://github.com/braillespecs/obfl/issues/48.

**Comment by josteinaj** [comment]
@matskober Is this a problem or more of a question for curiositys sake?

**Comment by matskober** [comment]
Well, both; it seems to me that elements from the DTBook frontmatter, such as a preface, behave wrongly: No page number and wider margins (or a block indent, I don't know)

**Comment by josteinaj** [comment]
Do we need to do anything here?

**Comment by josteinaj** [comment]
I'm closing this. I don't think it's a problem but we can open it again later if it is.
