### ISSUE TITLE
The first page of "real" content starts at a left hand page

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#59]
*from Trello (@matskober):*

- The first page of "real" content ,e.g. chapther 1, starts at a left hand page and is paginated as page zero (should be right hand and page number 1)
- toc is also to start at a right hand page

**Comment by bertfrees** [comment]
Which test can I use for this?

**Comment by matskober** [comment]
@bertfrees This is what we talked about earlier? If we get page number right, it would turn out ok?

**Comment by bertfrees** [comment]
I remember but I'm not sure if fixing https://github.com/nlbdev/pipeline/issues/56 would fix this issue because I'm also not 100% sure I know what the issue is exactly. An example would make it more clear.

**Comment by josteinaj** [comment]
I'm closing this as it's unclear what the difference is from #78 and it may have already be fixed in #56. The discussion can continue on #78 if needed.
