### ISSUE TITLE
Clean up tests a bit

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#6]
_From @bertfrees on March 2, 2016 18:50_

- [x] test_translator.xprocspec is failing.
- [x] If possibly remove or replace pending tests, otherwise explain why it is pending.
- [x] test_css_formatter.xprocspec isn't really testing anything from this module. Better would be to turn this into a script test, or move it to pipeline-mod-braille.
- [x] The expected result of some tests hasn't been verified.
- [x] The default CSS could use some more tests.
- [x] test_script.xprocspec should be remove because now we have test_dtbook-to-pef.xprocspec etc.
- [x] test_dtbook-to-pef.xprocspec should ideally not contain any embedded CSS, it should use as much as possible the default CSS and options.
- [x] use `x:pef-compare` from http://www.daisy.org/pipeline/modules/braille/pef-utils/library.xpl because more robust.

_Copied from original issue: nlbdev/pipeline-mod-nlb#24_

**Comment by josteinaj** [comment]
I agree. I'll have a look at it.

**Comment by josteinaj** [comment]
CC @usama49

**Comment by josteinaj** [comment]
_From @bertfrees on March 25, 2016 11:21_

Updated list of things to do.

**Comment by josteinaj** [comment]
Will use `x:pef-compare` when needed, but in many cases I like to select just portions of the output to be used for comparisons and then it's not needed. Considering that done for now.

Created a new issue for "The default CSS could use some more tests". There's other issues that are more important, but I'd like to track it as an issue anyway. See: #77

**Comment by bertfrees** [comment]
OK looks much better.

I know for sure that some test results are still wrong, for instance the page numbering, but we'll fix those when we get to it.

**Comment by bertfrees** [comment]
The test "Automatic numbering of notes" (added in https://github.com/nlbdev/pipeline-mod-nlb/commit/04482a5f82fa4b716cfc96abc4f9d05dba93f84e) also looks very suspicious.
