### ISSUE TITLE
Text in chapter without <h1> should start on row 6

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#61]
*from Trello (@matskober):*

Tried to adjust css with level1.chapter to control  some margin in top, to avoid  the chapter to start at first line (no hx in this book). It did not work ...

**Comment by josteinaj** [comment]
@usama49 could you have a look at this?

**Comment by josteinaj** [comment]
@matskober could you provide a short example?

**Comment by matskober** [comment]
[results (10).zip](https://github.com/nlbdev/pipeline/files/1131115/results.10.zip)

Tried to address level1, adding 'margin-top: 5;' did not succeed

**Comment by KariRudjord** [comment]
When no `<hx>` is present and chapter is only marked with `<level1>` text should start on line 5, @josteinaj

**Comment by josteinaj** [comment]
Ok, thanks, I'll create a test.

**Comment by KariRudjord** [comment]
Chapters without heading: text should start on row 6.

**Comment by KariRudjord** [comment]
Working.
