### ISSUE TITLE
h2 should behave as h1 when class=part

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#62]
*from Trello (@matskober):*

![ramme_h1](https://user-images.githubusercontent.com/295481/27594090-317249ca-5b59-11e7-96ab-484f3cbe3a39.PNG)

h1 by part should have a frame around itself. In the image "ramme_h1.png" the text in h1 has stretched itself all the way out to the frame. It must therefore be a margin or something around the text inside the frame.

![ramme_h1_eks2](https://user-images.githubusercontent.com/295481/27594172-6d4a154a-5b59-11e7-87cc-807a5613440c.PNG)

The book in this example is based on a not quite good structure; it consists of three parts, but the parts has variations on level2 - both when it regards the number of chapters, and also usage of h2. As the image "ramme_h1_eks2" shows, this means a difference in the presentation of h1. This is related to the principle that h2 should behave like h1 if class=part. We struggled with the same in NorBraille, so I suggested that we move focus over to `<level2>`; that it isn't the headline that forces a pagebreak.

When I produce the same book based on EPUB, the problem with pagebreaks are not present.

**Comment by josteinaj** [comment]
@matskober is this still an issue?

**Comment by matskober** [comment]
I believe this an NorBraille/DTBook issue mostly. So no.

**Comment by josteinaj** [comment]
Ok, then I'm closing it.
