### ISSUE TITLE
"-obfl-..." volume breaking rules doesn't work

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#63]

**Comment by bertfrees** [comment]
Is there a test for this?

**Comment by josteinaj** [comment]
No. I'll put it on my TODO to make a test for it.

**Comment by bertfrees** [comment]
It may be a real book for now (vs. a proper unit test) and I don't need the expected PEF. If you want to be more specific maybe just add a description in words of what is expected.

**Comment by josteinaj** [comment]
ok

**Comment by josteinaj** [comment]
I'm attaching the CSS file with volume breaking rules that gave the error previously (txt file extension since github won't allow css). However, I'm not getting the error now. Maybe something has been fixed after updating to the newer version?

@matskober have you tried with the volume breaking CSS with the new version?

[hefteinndeling.txt](https://github.com/nlbdev/pipeline/files/1115423/hefteinndeling.txt)

**Comment by matskober** [comment]
@josteinaj I just tried to add a css with a 'page-break-before: always' on level, but it don't happen

**Comment by bertfrees** [comment]
@matskober page-break-before is only about page breaking, does not have to do with volume breaking.

**Comment by josteinaj** [comment]
@matskober Ok, that's good. Could you try with the hefteinndeling.css file I sent you earlier (and linked to in my previous post here) and see is there's any errors, and if not, if the output looks good?

**Comment by matskober** [comment]
@brert @josteinaj Of course; I did mean volume-brak-before.

**Comment by bertfrees** [comment]
I'm pretty sure that `volume-break-before:always` works because SBS has been using that property successfully. Again, an example that shows it doesn't work would be great.

**Comment by matskober** [comment]
@bertfrees Yes, it seems to, when I tried it in the 'hefetinndeling.css'

**Comment by matskober** [comment]
@bertfrees 
I tried to avoid a volume-break-before in the first occurrence of level1 by addressing the id (#ch1-1), but then it failed (Job 465). Is not 'avoid' implemented? (also tried level1#ch1-1)(Job464)

**Comment by bertfrees** [comment]
No, `volume-break-before: avoid` is not implemented unfortunately. If you just want to reset the `volume-break-before: always` you could use `auto`:

```css
level1#ch1-1 {
    volume-break-before: auto;
}
```

I'll check why your job failed.

**Comment by bertfrees** [comment]
Anyway, because `#ch1-1` is the very first chapter I don't think it makes sense to put a `volume-break-before: avoid` on it because it would never start in the second volume. That would mean that the first chapter has only pre-content and I don't think Dotify ever does that. I need to test it to be sure though.

**Comment by matskober** [comment]
No, I wanted to make an exception, so that the first level1 did not trigger a new volume.

**Comment by bertfrees** [comment]
OK, in that case `auto` should be enough:

```css
bodymatter > level1:not(:first-child) {
    volume-break-before: auto;
}
```

**Comment by bertfrees** [comment]
Now it seems to work. Every level1 in its own volume.  The error you get when omitting the `level1:not(:first-child)` rule is a bit cryptic, that should ideally become a warning with a bit more explanation.

**Comment by josteinaj** [comment]
With `level1:not(.part), level1.part > level2 { volume-break-inside: -obfl-keep(8); }`, the tests with tables started failing with `Processing terminated by xsl:message at line 2065 in css-to-obfl.xsl`. There's not yet any good table CSS (awaiting #8 and #45), the current CSS just sets the table to be displayed as a block. So maybe that block gets too big and the system struggles with finding a good place for that big block? Just a thought.

**Comment by josteinaj** [comment]
see pending tests in 9553b9dff9315caf53a2c423aadd2429d7a406f2

**Comment by josteinaj** [comment]
@bertfrees I tried with your latest commits. I see you enabled the table-related non-volume-breaking tests that previously failed and they are working now. I'm still getting an error when using `-obfl-keep` in the small/medium/big volume breaking test though.

At first I got some output, but I had to add/remove paragraphs for the tests to be correct, and then they started throwing errors again.

Updated tests: https://github.com/nlbdev/pipeline/commit/dc406601e0f1dd897830aae389f1884039763333

Error:

```
(...)
13:20:41.066 [main] WARN  o.d.d.f.impl.EvenSizeVolumeSplitter - Could not fit contents even when adding a new volume.
13:20:41.066 [main] INFO  o.d.d.formatter.impl.VolumeProvider - Things didn't add up, running another iteration (10)
13:20:41.075 [main] ERROR o.d.p.b.d.c.impl.OBFLToPEFStep - dotify:obfl-to-pef failed
java.lang.RuntimeException: Failed to complete volume division.
	at org.daisy.dotify.formatter.impl.FormatterImpl.getVolumes(FormatterImpl.java:153) ~[dotify.formatter.impl-3.2.0-SNAPSHOT.jar:na]
	at org.daisy.dotify.formatter.impl.FormatterImpl.write(FormatterImpl.java:123) ~[dotify.formatter.impl-3.2.0-SNAPSHOT.jar:na]
	at org.daisy.dotify.engine.impl.LayoutEngineImpl.convert(LayoutEngineImpl.java:128) ~[dotify.formatter.impl-3.2.0-SNAPSHOT.jar:na]
	at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:136) ~[dotify-formatter-1.12.0-SNAPSHOT.jar:na]
(...)
```

**Comment by josteinaj** [comment]
Note: commenting out this line gets rid of the error but volumes would then not be divided in a good way:

https://github.com/nlbdev/pipeline/blob/dc406601e0f1dd897830aae389f1884039763333/modules/nlb/book-to-pef/src/main/resources/css/nlb-default.scss#L113

```css
level1:not(.part), level1.part > level2 {
    volume-break-inside: -obfl-keep(8);
}
```

**Comment by bertfrees** [comment]
Thanks, I'll have a look.

**Comment by bertfrees** [comment]
@josteinaj I pushed a fix.

**Comment by josteinaj** [comment]
Great! I will test some more.

**Comment by josteinaj** [comment]
The "*with parts: fit small chapters in same volume, medium chapters in separate volume, and big chapters in multiple volumes*"-test still gives the error in #68. I suppose this issue and #68 are the same issue. Here's the latest exception I get (as of b8f8b717a33b676825e2a0f4201456605b52e5de by enabling the pending volume breaking test):

```
(...)
11:42:30.117 [main] INFO  o.d.d.engine.impl.LayoutEngineImpl - Rendering output...
11:42:30.289 [main] INFO  o.d.d.formatter.impl.VolumeProvider - Things didn't add up, running another iteration (1)
11:42:30.310 [main] INFO  o.d.d.formatter.impl.VolumeProvider - Things didn't add up, running another iteration (2)
11:42:30.328 [main] INFO  o.d.d.formatter.impl.VolumeProvider - Things didn't add up, running another iteration (3)
11:42:30.345 [main] INFO  o.d.d.formatter.impl.VolumeProvider - Things didn't add up, running another iteration (4)
11:42:30.360 [main] WARN  o.d.d.f.impl.EvenSizeVolumeSplitter - Could not fit contents even when adding a new volume.
11:42:30.360 [main] INFO  o.d.d.formatter.impl.VolumeProvider - Things didn't add up, running another iteration (5)
11:42:30.376 [main] WARN  o.d.d.f.impl.EvenSizeVolumeSplitter - Could not fit contents even when adding a new volume.
11:42:30.376 [main] INFO  o.d.d.formatter.impl.VolumeProvider - Things didn't add up, running another iteration (6)
11:42:30.392 [main] WARN  o.d.d.f.impl.EvenSizeVolumeSplitter - Could not fit contents even when adding a new volume.
11:42:30.392 [main] INFO  o.d.d.formatter.impl.VolumeProvider - Things didn't add up, running another iteration (7)
11:42:30.402 [main] WARN  o.d.d.f.impl.EvenSizeVolumeSplitter - Could not fit contents even when adding a new volume.
11:42:30.402 [main] INFO  o.d.d.formatter.impl.VolumeProvider - Things didn't add up, running another iteration (8)
11:42:30.414 [main] WARN  o.d.d.f.impl.EvenSizeVolumeSplitter - Could not fit contents even when adding a new volume.
11:42:30.414 [main] INFO  o.d.d.formatter.impl.VolumeProvider - Things didn't add up, running another iteration (9)
11:42:30.427 [main] WARN  o.d.d.f.impl.EvenSizeVolumeSplitter - Could not fit contents even when adding a new volume.
11:42:30.427 [main] INFO  o.d.d.formatter.impl.VolumeProvider - Things didn't add up, running another iteration (10)
11:42:30.439 [main] ERROR o.d.p.b.d.c.impl.OBFLToPEFStep - dotify:obfl-to-pef failed
java.lang.RuntimeException: Failed to complete volume division.
	at org.daisy.dotify.formatter.impl.FormatterImpl.getVolumes(FormatterImpl.java:153) ~[dotify.formatter.impl-3.2.0-SNAPSHOT.jar:na]
	at org.daisy.dotify.formatter.impl.FormatterImpl.write(FormatterImpl.java:123) ~[dotify.formatter.impl-3.2.0-SNAPSHOT.jar:na]
	at org.daisy.dotify.engine.impl.LayoutEngineImpl.convert(LayoutEngineImpl.java:128) ~[dotify.formatter.impl-3.2.0-SNAPSHOT.jar:na]
	at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:136) ~[dotify-formatter-1.12.0-SNAPSHOT.jar:na]
(...)
```

**Comment by josteinaj** [comment]
Instead of removing the `-obfl-keep` rule, increasing the `maximum-number-of-sheets` also gets rid of the error. But since it works with `maximum-number-of-sheets = 4` without the `-obfl-keep` rule, I would expect it should work *with* the `-obfl-keep` rule as well.

**Comment by bertfrees** [comment]
This was because the latest version of Dotify was not picked up by the NLB tests. The test succeeds now.

**Comment by josteinaj** [comment]
I think we can close this issue now. After all of @bertfrees' fixes, volume breaking (including the -obfl-keep rules) seems to work pretty well.
