### ISSUE TITLE
Braille CSS: "Om boka" needs a check

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#65]
Both layout and text on page need some adjustments

**Comment by usama49** [comment]
@KariRudjord Can you  write required adjustments

**Comment by KariRudjord** [comment]
Slik skal det være i fullskrift:

ccccccccccc (h1)
Om boka
ccccccccccc

Fullskrift.
Punktskriftsidetall midtstilt nederst på siden.
Der sidetall fra utgave i visuell skrift er med, står dette høyrestilt nederst på siden.
Boka skal ikke returneres.
Feil og mangler kan meldes til punkt@nlb.no

Slik skal det være i kortskrift 1:
ccccccccccc (h1)
Om boka
ccccccccccc

Kortskrift nivå 1.
Punktskriftsidetall midtstilt nederst på siden.
Der sidetall fra utgave i visuell skrift er med, står dette høyrestilt nederst på siden.
Boka skal ikke returneres.
Feil og mangler kan meldes til punkt@nlb.no

Slik skal det være i kortskrift nivå 2:
ccccccccccc (h1)
Om boka
ccccccccccc

Kortskrift nivå 2.
Punktskriftsidetall midtstilt nederst på siden.
Der sidetall fra utgave i visuell skrift er med, står dette høyrestilt nederst på siden.
Boka skal ikke returneres.
Feil og mangler kan meldes til punkt@nlb.no

Slik skal det være i kortskrift nivå 3:
ccccccccccc (h1)
Om boka
ccccccccccc

Kortskrift nivå 3.
Punktskriftsidetall midtstilt nederst på siden.
Der sidetall fra utgave i visuell skrift er med, står dette høyrestilt nederst på siden.
Boka skal ikke returneres.
Feil og mangler kan meldes til punkt@nlb.no

@matskober Hvis du er uenig i ordlyden, er det bare å redigere!
@usama49 Jeg oppdaget at teksten var ulik etter forkortninggrad. Teksten over er den riktige. Opplysninger om antall sider/hefter kommer vi til å flytte til forsiden.

**Comment by josteinaj** [comment]
This colophon, as well as the titlepage, should probably be uncontracted.

**Comment by josteinaj** [comment]
Updated in 84739a2217bcc9cbd441294e2f5f56e3a6c28f6e and 02ab17fccbaa7533c675445fa57eb149307a3180.
