### ISSUE TITLE
test_translator/test_css_translator: px:transform sets xml:lang="no-Brai"

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#67]
I don't understand why this happens, but it seems to happen when `px:transform` is invoked:

```
<px:transform query="(input:css)(input:html)(output:css)(translator:nlb)(locale:no)(grade:1)(dots:6)"/>
```

It happens just in these two xprocspec tests where `px:transform` is invoked directly. I don't think it always happens either, so something must trigger it in some of the tests (css rule maybe?).

**Comment by bertfrees** [comment]
Yes I know. I have fixed the test locally. It happens always, nothing to do with CSS.

**Comment by bertfrees** [comment]
Tests are fixed.

**Comment by josteinaj** [comment]
bd340ea74ea2ee1805940ad243dbef10401b3cbd
