### ISSUE TITLE
Use NLB tables from upstream

### ISSUE THREAD

**Issue by bertfrees** [nlbdev/pipeline#69]
If they are not in sync with upstream we need to do more PRs. Currently it's hard to see how the files differ from upstream. It might be a better idea, since we have the super-repo now, to change the tables within the Liblouis source itself. This would depend on https://github.com/daisy/pipeline-mod-braille/issues/152.

**Comment by josteinaj** [comment]
I think this is done?

**Comment by bertfrees** [comment]
Yep
