### ISSUE TITLE
Dot-56 sometimes missing

### ISSUE THREAD

**Issue by bertfrees** [nlbdev/pipeline#70]
E.g., `a ble at l` translates to `⠰⠁ ⠃ ⠁ ⠇` sometimes instead of the correct `⠰⠁ ⠃ ⠁ ⠰⠇`. At first I thought the wrong translation was triggered by a previous translation, but after some investigation it turns out it can happen randomly.

Start with updating to latest version of Liblouis because it might be a bug that has been fixed already.

**Comment by josteinaj** [comment]
Note: the translation uses grade 1 contraction, so it might be related to some contraction rules. "⠰" is used to signal that a character is a single character, and not a contracted word.

**Comment by bertfrees** [comment]
This seems to have been fixed by updating to Liblouis 3.2.0. I'm not sure whether the bug was actually fixed are just "doesn't happen anymore". We can't be sure since it was a random thing.
