### ISSUE TITLE
Nested languages and contraction grade

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#73]
When contraction is enabled, only norwegian text should be contracted. This generally works fine since we set `text-transform: unconctracted;` on other languages during pre-processing. However, since there's no `text-transform` value for setting the contraction grade that I'm aware of, there's no straight forward way to reenable contraction when there's norwegian text inside other languages. I'm not sure if this is really that important though (will this ever happen in our books?).

```xml
<div xml:lang="no">
    <p>contracted</p>
    
    <div xml:lang="en">
        <p>not contracted</p>
        
        <div xml:lang="no">
            <p>should ideally be contracted but is not</p>
        </div>
    </div>
</div>
```

@KariRudjord any opinion on this?

**Comment by KariRudjord** [comment]
@josteinaj : I don't think contracted braille in foreign languages is something we will prioritize. We will be happy just to get uncontracted english braille in PIP. So this is not an important issue.

**Comment by josteinaj** [comment]
Ok. I'll move it to out-of-scope/backlog for now then.
