### ISSUE TITLE
Double linespacing not working in frontmatter

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#75]
Get the message "Error: assertion failed: [Rule 1] Rows do not fit within the defined page height" message.  Job 448

**Comment by bertfrees** [comment]
Is this again the old error that happens when double line spacing is combined with a footer?

See https://github.com/brailleapps/dotify/issues/196

**Comment by KariRudjord** [comment]
I'm quite sure it worked alright before (so maybe a bug in the last update)

**Comment by bertfrees** [comment]
OK could I get an example file please?

**Comment by KariRudjord** [comment]
@bertfrees I tried now, job 513. It works when I try to open "Forhåndsvisning" but not when I open "PEF". Confusing for me, but that means it works. I guess it works to download result as well? I check tomorrow since the server is beeing updated.

**Comment by bertfrees** [comment]
The reason why the preview can be opened even though the PEF is invalid is because the script does not perform validation on the output PEF. I understand how that can be confusing. I think it would be a good idea to add PEF validation.

**Comment by matskober** [comment]
I changed the rowgap from 4 to 3, and then I cold open it with e2U. While open I changed the rowgap back to 4 and it looks ok in the eu2 preview.
But I wonder: when single line is rowgap '0', how come we blow it all the way up to rowgap 4?

**Comment by matskober** [comment]
I mean that rowgap 0 is used when the option is set to single line space, of cores.

**Comment by bertfrees** [comment]
This is explained in the PEF specification: http://files.pef-format.org/specifications/pef-2008-1/pef-specification.html

![Schematic illustration of dot-to-dot height, row height and row gap](http://files.pef-format.org/specifications/pef-2008-1/images/rendering.jpg)

**Comment by matskober** [comment]
So today's line space, when single, is due to the "missing" dots 78? E.g. 1/2 d; "dobbel linjeavstand" should then be 1d = rowgap 1? If we set it to rowgap 2 (2d or 1r), it well be similar to todays linespaceing, when "dobbel".

**Comment by bertfrees** [comment]
Not sure these are all questions I can answer. Today's "single" line spacing is indeed due to the missing dots 7 & 8. We would have to increase the line height when we want to have 8-dot braille. I don't know what to say to the other questions, all I know is that there once was the requirement to support "[line spacing between single and double](http://snaekobbi.github.io/requirements/v1.5/index.xhtml#4.4:76)" but this requirement was later cancelled.

**Comment by bertfrees** [comment]
@KariRudjord Thanks for the test. I see that the boxes "Vis punktskrift-sidenummer" and "Vis original-sidenummer" are both checked, so this means that there will be a footer line with the page numbers. And I am quite sure that double line spacing combined with footers has never worked before.

**Comment by KariRudjord** [comment]
I wasn't aware of that, @bertfrees Is it possible to fix within this sprint? It's not good for us to produce double line spacing without page numbers. I now remember that it has been an issue before. Unfortunately I then missed the word "footer", I thought it ment "foot notes", which probably never will happen. Isn't this a problem for all the countries?

**Comment by bertfrees** [comment]
No one else uses double line spacing at the moment, except Celia but as far as I know they don't have an issue.

I have asked Joel what the status of the issue is and offered to help if needed.

**Comment by bertfrees** [comment]
Should be fixed now.

**Comment by matskober** [comment]
[results (14).zip](https://github.com/nlbdev/pipeline/files/1251744/results.14.zip)
Job #745. Tested double linespacing on DTBook. Seems to work on bodymatter, but not on frontmatter. 
@KariRudjord @josteinaj @usama49

**Comment by josteinaj** [comment]
I think this works now. Please test.

**Comment by KariRudjord** [comment]
Working.
