### ISSUE TITLE
Info about missing print page numbers in "om boka"

### ISSUE THREAD

**Issue by matskober** [nlbdev/pipeline#76]
autodetect that before starting the conversion and disable page number / page markers if there are no page numbers
make that info available for *om boken* (ingen sidetall fra visuell utgave)

**Comment by josteinaj** [comment]
@KariRudjord you didn't put this as a requirement in https://github.com/nlbdev/pipeline/issues/81#issuecomment-333584542. Would you like to have "Ingen sidetall fra visuell utgave" in "Om boken" as in Mats' suggestion?
