### ISSUE TITLE
Margin when print page numbers are left out

### ISSUE THREAD

**Issue by KariRudjord** [nlbdev/pipeline#79]
When print page numbers is left out of a production, the margin shall still be 2 columns. Now it is 1 according to Jostein.

**Comment by bertfrees** [comment]
Can I get an example file please?

**Comment by josteinaj** [comment]
I'll create a test.

**Comment by josteinaj** [comment]
I can't reproduce it. I don't know why I saw it earlier. But I'll commit a test for it anyway.

**Comment by KariRudjord** [comment]
When I try, there are 2 columns in the margin, and I can't remember I've seen anything else when I have tested, @josteinaj

**Comment by josteinaj** [comment]
I'm closing this issue then. Maybe it was just in my imagination :)
