### ISSUE TITLE
java.lang.IllegalArgumentException: Volume sizes too uneven: [1, 1]

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#80]

**Comment by josteinaj** [comment]
See test here: https://github.com/nlbdev/pipeline/blob/6c17ab8d52df824ae561e6c791161f9b38a5e311/modules/nlb/book-to-pef/src/test/xprocspec/test_dtbook-to-pef_volume-breaking.xprocspec#L115

**Comment by bertfrees** [comment]
Thanks for the test I'll have a look.

**Comment by bertfrees** [comment]
I guess you meant this test: https://github.com/nlbdev/pipeline/blob/6c17ab8d52df824ae561e6c791161f9b38a5e311/modules/nlb/book-to-pef/src/test/xprocspec/test_dtbook-to-pef_volume-breaking.xprocspec#L83

**Comment by bertfrees** [comment]
This error is caused by a `break-before="volume"` on the very first `sequence`. Dotify does not seem to handle that. This is not a problem, just something we have to take into account. I'll make the css-to-obfl conversion omit the `break-before` if it's the first sequence.
