### ISSUE TITLE
Move original colophon to end of rearmatter

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#82]
For DTBook, extract `<level1 class="colophon">`, for EPUB, extract `<body epub:type="colophon">`, and move to the end of the book (end of `<rearmatter>` for DTBook, and equivalent for EPUB).

If there's no headline, insert `<h1>Kolofon</h1>` for norwegian books and `<h1>Colophon</h1>` for english books (at the top of the `<level>`/`<body>`).

Do this as part of pre-processing. The colophon here refers to the one in the input book. A simpler colophon is generated for the braille version and inserted at the start of the book.

**Comment by KariRudjord** [comment]
Dublett
