### ISSUE TITLE
still counting from 1 on new section?

### ISSUE THREAD

**Issue by matskober** [nlbdev/pipeline#84]
<img width="331" alt="still counting sections from 1" src="https://user-images.githubusercontent.com/8014898/27910974-55c37f36-624f-11e7-98f3-746648112e3d.PNG">
[results (5).zip](https://github.com/nlbdev/pipeline/files/1127823/results.5.zip)
@josteinaj @bertfrees

**Comment by bertfrees** [comment]
There haven't been any changes to the layout since https://github.com/nlbdev/pipeline/issues/78#issuecomment-313044387.

**Comment by josteinaj** [comment]
closing as duplicate of #78
