### ISSUE TITLE
Avoid volume breaking within paragraphs

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#86]
I haven't quite managed to get this working yet. We'll have to fiddle some more with `volume-break-inside: -obfl-keep(...);` and see if we can get it working. I don't know if this will be a problem in real productions or not.

**Comment by bertfrees** [comment]
This is not supported yet, remember? Joel is working on that feature.

**Comment by josteinaj** [comment]
Yes I remember, but I thought I could get close with `-obfl-keep`.

**Comment by bertfrees** [comment]
Right. OK. What you can achieve with this is that the formatter might decide to split after the next sheet or the previous sheet if the current sheet ends in the middle of a paragraph _and if the next or previous doesn't_. But I think in braille chances are pretty low that a paragraph ends exactly at the end of a sheet (even with the `widows` and `orphans` properties) so I'm not sure how much this would help.

**Comment by KariRudjord** [comment]
Make a rule that says always divide outside a `<p>` if possible? Or divide between two sentences?

**Comment by matskober** [comment]
Job#1507

Volume break inside a note (Volume 3-4)
[558447 (2).zip](https://github.com/nlbdev/pipeline/files/1474665/558447.2.zip)

 @josteinaj @bertfrees

**Comment by bertfrees** [comment]
Avoiding volume breaking within paragraphs or sentences is not possible at the moment.

**Comment by matskober** [comment]
OK?

Could I apply it on the section that contains notes in the end of the
volume? (Strange thou, that notes defined to appear in the end of a volume
shows up in the beginning of the next; a splitting point must already have
been found, since the notes have been placed there in the first place?)

**Comment by bertfrees** [comment]
My comment was meant as an answer to Kari's comment from last week actually. Haven't looked at your case yet. If it's a an end-of-volume notes section, it would indeed be very strange that it is split over two volumes.

**Comment by matskober** [comment]
🙂

**Comment by bertfrees** [comment]
When I try to use the new Dotify feature to avoid volume breaks inside blocks, I get very strange behavior in some tests. I think I'll report this to Joel first before trying to figure it out myself.

**Comment by bertfrees** [comment]
I was able to create a minimal test case which I will send to Joel: https://github.com/sbsdev/dotify.formatter.impl/commit/60ce842c28cab4a6361492f453e80e9abc8ef778.

**EDIT**: also created an issue: https://github.com/brailleapps/dotify.formatter.impl/issues/50

**Comment by KariRudjord** [comment]
Also avoid volume break inside these if possible:
- list
- table
- poem
- blockquote
- sidebar
- caption

**Comment by josteinaj** [comment]
I hope this will be less of an issue with the new volume breaking rules based on leaf sections.

**Comment by bertfrees** [comment]
Not sure how this would help.

**Comment by josteinaj** [comment]
If the leaf sections are always small enough to fit in a volume, there shouldn't be a need for the formatter to break within a leaf section?

**Comment by bertfrees** [comment]
But leaf sections can still start in the middle of a page, so in this case a volume can not be broken exactly in between the two sections. There will still be some content of the first section in the next volume, or the other way around.

**Comment by josteinaj** [comment]
Ah, that was the issue, I had forgotten the details. I see how leaf sections won't matter then.

**Comment by KariRudjord** [comment]
1. I've seen volume break in the middle of a word in several productions, and I have got complaints from readers on this matter. Is it possible to do something to avoid it without making changes to Dotify? 562697/119897 is one example where almost every new volume start in a middle of a word or in the middle of a sentence. The best would be if every new volume start with a new `<p>`, but I guess that has to be changed in Dotify to work?

2. Is the same volume break rules implemented for contracted braille as for uncontracted braille?

**Comment by bertfrees** [comment]
1. Avoiding volume breaks inside words can be done with the `allow-ending-volume-on-hyphen` parameter. I can set this parameter if you want. I can't do anything about the other problems until the Dotify issue is resolved.

2. I think so yes. Should it be different?

**Comment by KariRudjord** [comment]
1. Yes, please! 
2. No, just checking. The person complaining have read several books in contracted braille grade 2.

**Comment by josteinaj** [comment]
Not sure if this is fixed in the newer versions or not, but if it is, I'm sure it will be followed in the official Pipeline 2 project instead, and not here.
