### ISSUE TITLE
CSS: braille page number; counter set

### ISSUE THREAD

**Issue by matskober** [nlbdev/pipeline#90]
```
bodymatter, body:not([epub|type~='cover']):not([epub|type~='frontmatter']):not([epub|type~='backmatter']) {
       page: body;
       counter-set: page 1;
}
```

@usama49 : Could you look in to this? 

The braille page number now starts counting 1 at the front page of each volume (this is not as it should be.), and at 1 on the first element in the DTBook's bodymatter (this counting runs thru out all volumes - only the generated pages in the beginning of each volume - as it shall).  

The braille page number 1 should appear at the bottom of the first non-generated page in the first volume, regardless of whether  this element is in the front or bodymatter of the DTBook. e.g. should a preface have braille pagination.

The generated pages are not to have any page numbers!

**Comment by josteinaj** [comment]
Closing and moving comments to #78
