### ISSUE TITLE
Letters become numers

### ISSUE THREAD

**Issue by matskober** [nlbdev/pipeline#92]
@josteinaj @usama49 @KariRudjord ⠀⠀⠀⠀⠀⠀
[job#700.zip](https://github.com/nlbdev/pipeline/files/1222071/job.700.zip)

The second sentence in this novel comes out all wrong; The 'J' in 'Jeg vet ikke...' is translated to number 6 (⠼⠋) !

Also, elements from the DTBook frontmatter, is represented twice @josteinaj @usama49 @josteinaj  
⠀⠀
```xml
<level2 id="level2_1" class="chapter"> 
    <p>Jeg stoler ikke p&#xe5; noen.</p> 
    <p>Jeg vet ikke, det er vel en slags skade.</p> 
    <p>Nei, ikke p&#xe5; deg heller. (...)</p>
    (...)
</level2>
```

```
⠀⠀⠀⠀⠠⠚⠑⠛⠀⠎⠞⠕⠇⠑⠗⠀⠊⠅⠅⠑⠀⠏⠡⠀⠝⠕⠑⠝⠄⠀⠀⠀
⠀⠀⠀⠀⠼⠋⠰⠑⠛⠀⠧⠑⠞⠀⠊⠅⠅⠑⠂⠀⠙⠑⠞⠀⠑⠗⠀⠧⠑⠇⠀⠀
⠀⠀⠑⠝⠀⠎⠇⠁⠛⠎⠀⠎⠅⠁⠙⠑⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠠⠝⠑⠊⠂⠀⠊⠅⠅⠑⠀⠏⠡⠀⠙⠑⠛⠀⠓⠑⠇⠇⠑⠗⠄⠀
```

Weird braille also in generated text, again letters turned into numbers.

 
--
012llskrift
012tall _sider: 0339
05oka skal ikke returneres'
_feil eller mangler kan
meldes til 2punkt^nlb'no'[

**Comment by josteinaj** [comment]
That's strange. I'll try to reproduce it when I get the time.

**Comment by josteinaj** [comment]
This works for me when I re-run job 700 now. The "`⠼⠋⠰⠑⠛ / #f|eg`" has now become "`⠠⠚⠑⠛ / ´jeg`.
