### ISSUE TITLE
Problem with hebrew braille

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/pipeline#96]
from @matskober:
> For some reason, hebrew is "incorporated" in the norwegian liblouis-table; can it be used?

**Comment by KariRudjord** [comment]
Hebrew braille is not prioritized.

**Comment by matskober** [comment]
OK; NLBs prioriteringer skal jeg ikke blande meg inn i! Jeg driver og lærer
meg hebraisk, så siden jeg hadde  lagt merke til at hebraisk var del av den
norske liblouis tabellen, og fordi det var et issue med innskuttet
sekvenser på avvikende språk / tospråklige braillebøker, fant jeg det
interessant og relevant.

Mats

**Comment by josteinaj** [comment]
Hebraiske tegn ser ut til å være definert i den norske 8-punktstabellen. Så dette er nok ikke hebraisk punktstandard, men hebraiske tegn i følge norsk punktstandard:
https://github.com/liblouis/liblouis/blob/275b28883c49aa691306430549a17be781fe360e/tables/no-no-8dot.utb#L334

Standarden dette er hentet fra er den norske punkttabellen for JAWS fra 2011: https://github.com/liblouis/braille-specs/tree/master/norwegian
