### ISSUE TITLE
Ensure that page numbering works the same way in both DTBook and EPUB3

### ISSUE THREAD

**Issue by matskober** [nlbdev/pipeline#97]
I produced the same title both as DTbook to pef (job951) and EPUB3 to pef (job952). Only adjustment done, was setting max sheets to 35.  When using EPUB3, the braille page number starts again (at 1) in every volume. 

@josteinaj @bertfrees @usama49 @KariRudjord 
[job952.zip](https://github.com/nlbdev/pipeline/files/1340807/job952.zip)
[job951.zip](https://github.com/nlbdev/pipeline/files/1340808/job951.zip)

**Comment by josteinaj** [comment]
Replaced by #23.
